# LIMPIEZA DE DATOS — IPC
### Índice de Precios de Consumo, base 2021 (be2621)
### Incluye:
- Importación de librerías
- Carga de datasets (formato Boletín Estadístico BdE)
- Conversión de tipos y limpieza
- Exportación de archivos finales

---
**Fuentes (Banco de España, Boletín Estadístico):**
- `Inflación, IPC, índice de Precios de consumo, base 2021, OCDE, be2621.csv`, *Índice de Precios de Consumo. Base 2021.* Cobertura: enero 1954 – marzo 2026. Mensual.

# 0. Importación de "Librerías"

In [76]:
import pandas as pd
import plotly.express as px

# 1. Carga de datasets

In [77]:
ruta = '../Fuentes/BDE/SB_IPC/'

### Serie de 1973 a 2026

In [78]:
df_54_25 = pd.read_csv(ruta + 'Inflación, IPC, índice de Precios de consumo, base 2021, OCDE, be2621.csv', encoding= 'latin1', header=6)
df_54_25

         fecha  Estadísticas Generales. IPC. España
0     1/1/1950                                  NaN
1     2/1/1950                                  NaN
2     3/1/1950                                  NaN
3     4/1/1950                                  NaN
4     5/1/1950                                  NaN
..         ...                                  ...
909  10/1/2025                               127.72
910  11/1/2025                               127.96
911  12/1/2025                               128.40
912   1/1/2026                                  NaN
913   2/1/2026                                  NaN

[914 rows x 2 columns]

In [79]:
df_54_25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 914 entries, 0 to 913
Data columns (total 2 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   fecha                                914 non-null    object
 1   Estadísticas Generales. IPC. España  862 non-null    float64
dtypes: float64(1), object(1)
memory usage: 14.4+ KB

In [80]:
df_54_25= df_54_25.dropna(subset='Estadísticas Generales. IPC. España')
df_54_25

         fecha  Estadísticas Generales. IPC. España
50    3/1/1954                                 1.79
51    4/1/1954                                 1.79
52    5/1/1954                                 1.79
53    6/1/1954                                 1.78
54    7/1/1954                                 1.78
..         ...                                  ...
907   8/1/2025                               127.20
908   9/1/2025                               126.84
909  10/1/2025                               127.72
910  11/1/2025                               127.96
911  12/1/2025                               128.40

[862 rows x 2 columns]

### Chequeo en conjunto

In [81]:
dataframes = [df_54_25]
df_54_25.attrs['nombre'] = 'df_54_25'

In [82]:
# Valores únicos de cada dataset para ver las categorías
for df in dataframes:
    print(f'Valores únicos en {df.attrs['nombre']}')
    for columna in df:
        print(df[columna].unique())

Valores únicos en df_54_25
['3/1/1954' '4/1/1954' '5/1/1954' '6/1/1954' '7/1/1954' '8/1/1954'
 '9/1/1954' '10/1/1954' '11/1/1954' '12/1/1954' '1/1/1955' '2/1/1955'
 '3/1/1955' '4/1/1955' '5/1/1955' '6/1/1955' '7/1/1955' '8/1/1955'
 '9/1/1955' '10/1/1955' '11/1/1955' '12/1/1955' '1/1/1956' '2/1/1956'
 '3/1/1956' '4/1/1956' '5/1/1956' '6/1/1956' '7/1/1956' '8/1/1956'
 '9/1/1956' '10/1/1956' '11/1/1956' '12/1/1956' '1/1/1957' '2/1/1957'
 '3/1/1957' '4/1/1957' '5/1/1957' '6/1/1957' '7/1/1957' '8/1/1957'
 '9/1/1957' '10/1/1957' '11/1/1957' '12/1/1957' '1/1/1958' '2/1/1958'
 '3/1/1958' '4/1/1958' '5/1/1958' '6/1/1958' '7/1/1958' '8/1/1958'
 '9/1/1958' '10/1/1958' '11/1/1958' '12/1/1958' '1/1/1959' '2/1/1959'
 '3/1/1959' '4/1/1959' '5/1/1959' '6/1/1959' '7/1/1959' '8/1/1959'
 '9/1/1959' '10/1/1959' '11/1/1959' '12/1/1959' '1/1/1960' '2/1/1960'
 '3/1/1960' '4/1/1960' '5/1/1960' '6/1/1960' '7/1/1960' '8/1/1960'
 '9/1/1960' '10/1/1960' '11/1/1960' '12/1/1960' '1/1/1961' '2/1/1961'
 '3/1/1961' '4/1/1961' '5/1/1961' '6/1/1961' '7/1/1961' '8/1/1961'
 '9/1/1961' '10/1/1961' '11/1/1961' '12/1/1961' '1/1/1962' '2/1/1962'
 '3/1/1962' '4/1/1962' '5/1/1962' '6/1/1962' '7/1/1962' '8/1/1962'
 '9/1/1962' '10/1/1962' '11/1/1962' '12/1/1962' '1/1/1963' '2/1/1963'
 '3/1/1963' '4/1/1963' '5/1/1963' '6/1/1963' '7/1/1963' '8/1/1963'
 '9/1/1963' '10/1/1963' '11/1/1963' '12/1/1963' '1/1/1964' '2/1/1964'
 '3/1/1964' '4/1/1964' '5/1/1964' '6/1/1964' '7/1/1964' '8/1/1964'
 '9/1/1964' '10/1/1964' '11/1/1964' '12/1/1964' '1/1/1965' '2/1/1965'
 '3/1/1965' '4/1/1965' '5/1/1965' '6/1/1965' '7/1/1965' '8/1/1965'
 '9/1/1965' '10/1/1965' '11/1/1965' '12/1/1965' '1/1/1966' '2/1/1966'
 '3/1/1966' '4/1/1966' '5/1/1966' '6/1/1966' '7/1/1966' '8/1/1966'
 '9/1/1966' '10/1/1966' '11/1/1966' '12/1/1966' '1/1/1967' '2/1/1967'
 '3/1/1967' '4/1/1967' '5/1/1967' '6/1/1967' '7/1/1967' '8/1/1967'
 '9/1/1967' '10/1/1967' '11/1/1967' '12/1/1967' '1/1/1968' '2/1/1968'
 '3/1/1968' '4/1/1968' '5/1/1968' '6/1/1968' '7/1/1968' '8/1/1968'
 '9/1/1968' '10/1/1968' '11/1/1968' '12/1/1968' '1/1/1969' '2/1/1969'
 '3/1/1969' '4/1/1969' '5/1/1969' '6/1/1969' '7/1/1969' '8/1/1969'
 '9/1/1969' '10/1/1969' '11/1/1969' '12/1/1969' '1/1/1970' '2/1/1970'
 '3/1/1970' '4/1/1970' '5/1/1970' '6/1/1970' '7/1/1970' '8/1/1970'
 '9/1/1970' '10/1/1970' '11/1/1970' '12/1/1970' '1/1/1971' '2/1/1971'
 '3/1/1971' '4/1/1971' '5/1/1971' '6/1/1971' '7/1/1971' '8/1/1971'
 '9/1/1971' '10/1/1971' '11/1/1971' '12/1/1971' '1/1/1972' '2/1/1972'
 '3/1/1972' '4/1/1972' '5/1/1972' '6/1/1972' '7/1/1972' '8/1/1972'
 '9/1/1972' '10/1/1972' '11/1/1972' '12/1/1972' '1/1/1973' '2/1/1973'
 '3/1/1973' '4/1/1973' '5/1/1973' '6/1/1973' '7/1/1973' '8/1/1973'
 '9/1/1973' '10/1/1973' '11/1/1973' '12/1/1973' '1/1/1974' '2/1/1974'
 '3/1/1974' '4/1/1974' '5/1/1974' '6/1/1974' '7/1/1974' '8/1/1974'
 '9/1/1974' '10/1/1974' '11/1/1974' '12/1/1974' '1/1/1975' '2/1/1975'
 '3/1/1975' '4/1/1975' '5/1/1975' '6/1/1975' '7/1/1975' '8/1/1975'
 '9/1/1975' '10/1/1975' '11/1/1975' '12/1/1975' '1/1/1976' '2/1/1976'
 '3/1/1976' '4/1/1976' '5/1/1976' '6/1/1976' '7/1/1976' '8/1/1976'
 '9/1/1976' '10/1/1976' '11/1/1976' '12/1/1976' '1/1/1977' '2/1/1977'
 '3/1/1977' '4/1/1977' '5/1/1977' '6/1/1977' '7/1/1977' '8/1/1977'
 '9/1/1977' '10/1/1977' '11/1/1977' '12/1/1977' '1/1/1978' '2/1/1978'
 '3/1/1978' '4/1/1978' '5/1/1978' '6/1/1978' '7/1/1978' '8/1/1978'
 '9/1/1978' '10/1/1978' '11/1/1978' '12/1/1978' '1/1/1979' '2/1/1979'
 '3/1/1979' '4/1/1979' '5/1/1979' '6/1/1979' '7/1/1979' '8/1/1979'
 '9/1/1979' '10/1/1979' '11/1/1979' '12/1/1979' '1/1/1980' '2/1/1980'
 '3/1/1980' '4/1/1980' '5/1/1980' '6/1/1980' '7/1/1980' '8/1/1980'
 '9/1/1980' '10/1/1980' '11/1/1980' '12/1/1980' '1/1/1981' '2/1/1981'
 '3/1/1981' '4/1/1981' '5/1/1981' '6/1/1981' '7/1/1981' '8/1/1981'
 '9/1/1981' '10/1/1981' '11/1/1981' '12/1/1981' '1/1/1982' '2/1/1982'
 '3/1/1982' '4/1/1982' '5/1/1982' '6/1/1982' '7/1/1982' '8/1/1982'
 '9/1/1982' '10/1/1982' '11/1/1982' '12/1/1982' '1/1/1983' '2/1/1983'
 '3/1/1983' '4/1/1983' '5/1/1983' '6/1/1983' '7/1/1983' '8/1/1983'
 '9/1/1983' '10/1/1983' '11/1/1983' '12/1/1983' '1/1/1984' '2/1/1984'
 '3/1/1984' '4/1/1984' '5/1/1984' '6/1/1984' '7/1/1984' '8/1/1984'
 '9/1/1984' '10/1/1984' '11/1/1984' '12/1/1984' '1/1/1985' '2/1/1985'
 '3/1/1985' '4/1/1985' '5/1/1985' '6/1/1985' '7/1/1985' '8/1/1985'
 '9/1/1985' '10/1/1985' '11/1/1985' '12/1/1985' '1/1/1986' '2/1/1986'
 '3/1/1986' '4/1/1986' '5/1/1986' '6/1/1986' '7/1/1986' '8/1/1986'
 '9/1/1986' '10/1/1986' '11/1/1986' '12/1/1986' '1/1/1987' '2/1/1987'
 '3/1/1987' '4/1/1987' '5/1/1987' '6/1/1987' '7/1/1987' '8/1/1987'
 '9/1/1987' '10/1/1987' '11/1/1987' '12/1/1987' '1/1/1988' '2/1/1988'
 '3/1/1988' '4/1/1988' '5/1/1988' '6/1/1988' '7/1/1988' '8/1/1988'
 '9/1/1988' '10/1/1988' '11/1/1988' '12/1/1988' '1/1/1989' '2/1/1989'
 '3/1/1989' '4/1/1989' '5/1/1989' '6/1/1989' '7/1/1989' '8/1/1989'
 '9/1/1989' '10/1/1989' '11/1/1989' '12/1/1989' '1/1/1990' '2/1/1990'
 '3/1/1990' '4/1/1990' '5/1/1990' '6/1/1990' '7/1/1990' '8/1/1990'
 '9/1/1990' '10/1/1990' '11/1/1990' '12/1/1990' '1/1/1991' '2/1/1991'
 '3/1/1991' '4/1/1991' '5/1/1991' '6/1/1991' '7/1/1991' '8/1/1991'
 '9/1/1991' '10/1/1991' '11/1/1991' '12/1/1991' '1/1/1992' '2/1/1992'
 '3/1/1992' '4/1/1992' '5/1/1992' '6/1/1992' '7/1/1992' '8/1/1992'
 '9/1/1992' '10/1/1992' '11/1/1992' '12/1/1992' '1/1/1993' '2/1/1993'
 '3/1/1993' '4/1/1993' '5/1/1993' '6/1/1993' '7/1/1993' '8/1/1993'
 '9/1/1993' '10/1/1993' '11/1/1993' '12/1/1993' '1/1/1994' '2/1/1994'
 '3/1/1994' '4/1/1994' '5/1/1994' '6/1/1994' '7/1/1994' '8/1/1994'
 '9/1/1994' '10/1/1994' '11/1/1994' '12/1/1994' '1/1/1995' '2/1/1995'
 '3/1/1995' '4/1/1995' '5/1/1995' '6/1/1995' '7/1/1995' '8/1/1995'
 '9/1/1995' '10/1/1995' '11/1/1995' '12/1/1995' '1/1/1996' '2/1/1996'
 '3/1/1996' '4/1/1996' '5/1/1996' '6/1/1996' '7/1/1996' '8/1/1996'
 '9/1/1996' '10/1/1996' '11/1/1996' '12/1/1996' '1/1/1997' '2/1/1997'
 '3/1/1997' '4/1/1997' '5/1/1997' '6/1/1997' '7/1/1997' '8/1/1997'
 '9/1/1997' '10/1/1997' '11/1/1997' '12/1/1997' '1/1/1998' '2/1/1998'
 '3/1/1998' '4/1/1998' '5/1/1998' '6/1/1998' '7/1/1998' '8/1/1998'
 '9/1/1998' '10/1/1998' '11/1/1998' '12/1/1998' '1/1/1999' '2/1/1999'
 '3/1/1999' '4/1/1999' '5/1/1999' '6/1/1999' '7/1/1999' '8/1/1999'
 '9/1/1999' '10/1/1999' '11/1/1999' '12/1/1999' '1/1/2000' '2/1/2000'
 '3/1/2000' '4/1/2000' '5/1/2000' '6/1/2000' '7/1/2000' '8/1/2000'
 '9/1/2000' '10/1/2000' '11/1/2000' '12/1/2000' '1/1/2001' '2/1/2001'
 '3/1/2001' '4/1/2001' '5/1/2001' '6/1/2001' '7/1/2001' '8/1/2001'
 '9/1/2001' '10/1/2001' '11/1/2001' '12/1/2001' '1/1/2002' '2/1/2002'
 '3/1/2002' '4/1/2002' '5/1/2002' '6/1/2002' '7/1/2002' '8/1/2002'
 '9/1/2002' '10/1/2002' '11/1/2002' '12/1/2002' '1/1/2003' '2/1/2003'
 '3/1/2003' '4/1/2003' '5/1/2003' '6/1/2003' '7/1/2003' '8/1/2003'
 '9/1/2003' '10/1/2003' '11/1/2003' '12/1/2003' '1/1/2004' '2/1/2004'
 '3/1/2004' '4/1/2004' '5/1/2004' '6/1/2004' '7/1/2004' '8/1/2004'
 '9/1/2004' '10/1/2004' '11/1/2004' '12/1/2004' '1/1/2005' '2/1/2005'
 '3/1/2005' '4/1/2005' '5/1/2005' '6/1/2005' '7/1/2005' '8/1/2005'
 '9/1/2005' '10/1/2005' '11/1/2005' '12/1/2005' '1/1/2006' '2/1/2006'
 '3/1/2006' '4/1/2006' '5/1/2006' '6/1/2006' '7/1/2006' '8/1/2006'
 '9/1/2006' '10/1/2006' '11/1/2006' '12/1/2006' '1/1/2007' '2/1/2007'
 '3/1/2007' '4/1/2007' '5/1/2007' '6/1/2007' '7/1/2007' '8/1/2007'
 '9/1/2007' '10/1/2007' '11/1/2007' '12/1/2007' '1/1/2008' '2/1/2008'
 '3/1/2008' '4/1/2008' '5/1/2008' '6/1/2008' '7/1/2008' '8/1/2008'
 '9/1/2008' '10/1/2008' '11/1/2008' '12/1/2008' '1/1/2009' '2/1/2009'
 '3/1/2009' '4/1/2009' '5/1/2009' '6/1/2009' '7/1/2009' '8/1/2009'
 '9/1/2009' '10/1/2009' '11/1/2009' '12/1/2009' '1/1/2010' '2/1/2010'
 '3/1/2010' '4/1/2010' '5/1/2010' '6/1/2010' '7/1/2010' '8/1/2010'
 '9/1/2010' '10/1/2010' '11/1/2010' '12/1/2010' '1/1/2011' '2/1/2011'
 '3/1/2011' '4/1/2011' '5/1/2011' '6/1/2011' '7/1/2011' '8/1/2011'
 '9/1/2011' '10/1/2011' '11/1/2011' '12/1/2011' '1/1/2012' '2/1/2012'
 '3/1/2012' '4/1/2012' '5/1/2012' '6/1/2012' '7/1/2012' '8/1/2012'
 '9/1/2012' '10/1/2012' '11/1/2012' '12/1/2012' '1/1/2013' '2/1/2013'
 '3/1/2013' '4/1/2013' '5/1/2013' '6/1/2013' '7/1/2013' '8/1/2013'
 '9/1/2013' '10/1/2013' '11/1/2013' '12/1/2013' '1/1/2014' '2/1/2014'
 '3/1/2014' '4/1/2014' '5/1/2014' '6/1/2014' '7/1/2014' '8/1/2014'
 '9/1/2014' '10/1/2014' '11/1/2014' '12/1/2014' '1/1/2015' '2/1/2015'
 '3/1/2015' '4/1/2015' '5/1/2015' '6/1/2015' '7/1/2015' '8/1/2015'
 '9/1/2015' '10/1/2015' '11/1/2015' '12/1/2015' '1/1/2016' '2/1/2016'
 '3/1/2016' '4/1/2016' '5/1/2016' '6/1/2016' '7/1/2016' '8/1/2016'
 '9/1/2016' '10/1/2016' '11/1/2016' '12/1/2016' '1/1/2017' '2/1/2017'
 '3/1/2017' '4/1/2017' '5/1/2017' '6/1/2017' '7/1/2017' '8/1/2017'
 '9/1/2017' '10/1/2017' '11/1/2017' '12/1/2017' '1/1/2018' '2/1/2018'
 '3/1/2018' '4/1/2018' '5/1/2018' '6/1/2018' '7/1/2018' '8/1/2018'
 '9/1/2018' '10/1/2018' '11/1/2018' '12/1/2018' '1/1/2019' '2/1/2019'
 '3/1/2019' '4/1/2019' '5/1/2019' '6/1/2019' '7/1/2019' '8/1/2019'
 '9/1/2019' '10/1/2019' '11/1/2019' '12/1/2019' '1/1/2020' '2/1/2020'
 '3/1/2020' '4/1/2020' '5/1/2020' '6/1/2020' '7/1/2020' '8/1/2020'
 '9/1/2020' '10/1/2020' '11/1/2020' '12/1/2020' '1/1/2021' '2/1/2021'
 '3/1/2021' '4/1/2021' '5/1/2021' '6/1/2021' '7/1/2021' '8/1/2021'
 '9/1/2021' '10/1/2021' '11/1/2021' '12/1/2021' '1/1/2022' '2/1/2022'
 '3/1/2022' '4/1/2022' '5/1/2022' '6/1/2022' '7/1/2022' '8/1/2022'
 '9/1/2022' '10/1/2022' '11/1/2022' '12/1/2022' '1/1/2023' '2/1/2023'
 '3/1/2023' '4/1/2023' '5/1/2023' '6/1/2023' '7/1/2023' '8/1/2023'
 '9/1/2023' '10/1/2023' '11/1/2023' '12/1/2023' '1/1/2024' '2/1/2024'
 '3/1/2024' '4/1/2024' '5/1/2024' '6/1/2024' '7/1/2024' '8/1/2024'
 '9/1/2024' '10/1/2024' '11/1/2024' '12/1/2024' '1/1/2025' '2/1/2025'
 '3/1/2025' '4/1/2025' '5/1/2025' '6/1/2025' '7/1/2025' '8/1/2025'
 '9/1/2025' '10/1/2025' '11/1/2025' '12/1/2025']
[  1.79   1.78   1.8    1.82   1.83   1.84   1.85   1.86   1.87   1.88
   1.89   1.9    1.92   1.94   1.96   1.97   1.98   1.99   2.02   2.06
   2.09   2.11   2.12   2.13   2.16   2.19   2.22   2.27   2.3    2.33
   2.34   2.35   2.39   2.44   2.46   2.47   2.49   2.53   2.55   2.57
   2.6    2.61   2.62   2.64   2.65   2.66   2.67   2.68   2.7    2.69
   2.72   2.73   2.71   2.74   2.75   2.78   2.82   2.85   2.87   2.86
   2.88   2.91   2.98   3.02   3.03   3.05   3.11   3.12   3.07   3.1
   3.13   3.17   3.18   3.19   3.2    3.21   3.25   3.32   3.38   3.41
   3.47   3.55   3.59   3.62   3.68   3.71   3.74   3.76   3.8    3.82
   3.9    3.92   3.91   3.95   4.01   4.02   4.03   4.1    4.13   4.16
   4.18   4.24   4.25   4.22   4.28   4.29   4.31   4.4    4.41   4.46
   4.5    4.48   4.45   4.47   4.53   4.52   4.49   4.57   4.55   4.58
   4.59   4.63   4.68   4.7    4.69   4.72   4.75   4.74   4.83   4.9
   4.92   4.97   4.99   5.     5.05   5.1    5.16   5.19   5.21   5.22
   5.28   5.34   5.41   5.48   5.49   5.54   5.56   5.58   5.65   5.71
   5.79   5.83   5.84   5.88   5.93   5.94   5.99   6.07   6.16   6.25
   6.32   6.43   6.54   6.64   6.65   6.72   6.76   6.78   6.93   7.08
   7.17   7.2    7.29   7.41   7.52   7.6    7.81   7.92   8.03   8.11
   8.16   8.31   8.41   8.43   8.56   8.7    8.84   8.9    9.04   9.15
   9.25   9.46   9.65  10.1   10.04  10.18  10.37  10.52  10.71  10.83
  11.18  11.35  11.62  11.83  11.93  12.26  12.67  13.08  13.26  13.47
  13.57  13.68  13.9   14.04  14.22  14.52  14.66  14.81  15.13  15.39
  15.52  15.66  15.73  15.95  16.22  16.34  16.51  16.76  16.96  17.11
  17.48  17.65  17.88  18.12  18.17  18.43  18.94  19.11  19.21  19.4
  19.53  19.83  20.11  20.35  20.57  20.73  20.94  21.24  21.67  21.78
  22.21  22.43  22.54  22.56  23.    23.28  23.46  23.73  23.93  24.29
  24.8   24.99  25.24  25.57  25.94  26.19  26.52  26.71  26.74  27.01
  27.1   27.7   28.17  28.31  28.48  28.87  28.99  29.16  29.26  29.66
  29.89  30.3   30.61  31.08  31.56  31.68  31.94  32.09  32.26  32.49
  32.99  33.22  33.29  33.49  33.66  33.89  34.52  34.77  34.99  35.35
  35.46  35.4   35.6   35.65  36.04  36.23  36.51  36.66  37.71  37.88
  38.01  38.1   38.21  38.56  38.95  39.06  39.46  39.61  39.52  39.69
  39.99  40.16  40.39  40.48  40.43  40.44  40.85  40.84  41.21  41.46
  41.36  41.51  41.77  41.89  42.19  42.04  42.21  42.76  43.19  43.56
  43.61  43.59  43.94  44.45  44.48  44.76  44.88  44.95  45.19  45.92
  46.03  46.52  46.7   46.78  46.96  47.42  47.72  47.9   48.    48.15
  48.8   49.01  49.52  49.96  49.91  50.04  50.62  50.55  50.71  50.82
  50.97  51.11  51.75  51.94  52.37  52.69  52.77  52.8   53.64  54.
  54.19  54.14  54.28  54.27  54.44  54.94  55.39  55.43  55.46  55.63
  56.15  56.17  56.36  56.61  56.77  56.91  57.11  57.45  57.78  57.99
  58.09  58.37  58.96  58.98  59.17  59.41  59.53  59.59  59.82  60.21
  60.39  60.53  60.63  60.9   61.53  61.83  62.19  62.52  62.55  62.61
  62.62  62.79  63.04  63.16  63.32  63.53  63.92  64.09  64.32  64.68
  64.91  64.85  64.94  65.12  65.28  65.37  65.38  65.57  65.76  65.71
  65.75  65.77  65.87  65.86  65.99  66.28  66.6   66.58  66.71  66.89
  67.05  66.92  67.09  67.18  67.22  67.47  67.65  67.7   67.64  67.83
  68.08  68.12  68.42  68.67  68.69  68.98  69.28  69.41  69.38  69.5
  69.81  70.04  70.14  70.42  70.71  70.83  71.04  71.47  71.77  71.96
  72.14  72.32  72.57  72.6   72.84  73.14  73.52  73.8   74.05  74.23
  74.41  74.4   74.32  74.27  74.54  74.43  74.5   75.11  76.13  76.41
  75.88  76.1   76.38  77.14  77.26  77.52  77.2   77.36  77.9   78.53
  78.46  78.51  78.02  78.38  78.61  79.14  79.4   79.53  78.98  79.01
  79.56  80.65  81.13  81.26  80.64  81.    81.14  81.98  82.18  82.1
  81.41  81.62  82.27  83.45  83.61  83.81  83.29  83.66  84.17  84.86
  84.99  85.17  84.82  85.46  86.67  86.98  87.11  86.6   86.77  86.63
  87.2   87.44  86.85  86.91  87.57  88.78  89.02  89.19  88.54  88.66
  88.95  90.1   90.75  91.13  90.56  90.71  91.51  92.5   93.12  93.66
  93.21  93.01  92.99  93.31  92.91  92.44  91.3   91.31  91.46  92.35
  92.32  92.72  91.93  92.25  92.03  92.69  93.19  93.17  92.23  92.07
  92.75  93.74  93.95  94.11  93.69  93.93  93.99  94.85  95.37  95.95
  95.25  96.08  97.28  97.25  97.11  96.59  96.71  96.95  97.71  98.11
  98.23  97.15  97.91  99.28  99.14  98.95  98.72 100.25 101.11 100.98
 101.05  99.76  99.93 100.29 100.66 100.85 100.99 100.47 100.79 100.6
 101.01 101.22 101.31  99.96  99.92 100.14 101.03 101.08 100.13 100.44
 100.91 100.84  98.64  98.84  99.47 100.39 100.87 101.14 100.2   99.87
  99.56 100.56 100.27  98.36  98.01  99.33 100.33  99.6   99.73  99.74
 100.88 101.24 101.84 101.28 100.92 100.9  101.87 101.8  101.85 101.15
 101.35 101.52 102.46 102.93 102.97 101.86 102.   102.12 102.96 103.89
 104.16 103.42 103.57 103.82 104.78 104.66 104.19 102.86 103.11 103.49
 104.53 104.73 104.61 103.96 103.9  104.91 105.09 105.01 103.99 103.87
 103.47 103.78 104.25 103.32 103.37 103.52 104.06 104.23 104.46 104.47
 103.85 104.86 106.1  106.59 107.1  106.3  106.78 107.67 109.65 109.98
 111.3  110.87 111.77 115.15 114.95 115.9  118.04 117.74 117.22 117.62
 117.47 117.65 117.4  118.51 118.95 119.66 119.6  120.28 120.48 121.13
 121.34 121.69 121.27 121.3  121.4  121.83 122.76 123.62 123.94 124.41
 123.82 123.87 123.12 123.89 124.19 124.75 124.97 125.46 125.53 126.32
 126.41 127.25 127.15 127.2  126.84 127.72 127.96 128.4 ]

In [83]:
# Información acerca del tipo de dato y valores nulos de las columnas de cada dataset
for df in dataframes:
    print(f'Información acerca de {df.attrs['nombre']}')
    print(df.info())

Información acerca de df_54_25
<class 'pandas.core.frame.DataFrame'>
Index: 862 entries, 50 to 911
Data columns (total 2 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   fecha                                862 non-null    object
 1   Estadísticas Generales. IPC. España  862 non-null    float64
dtypes: float64(1), object(1)
memory usage: 20.2+ KB
None

# 2. Limpieza

### Transformación de los datos de fecha

In [84]:
df_54_25 = df_54_25.copy()
df_54_25['fecha'] = pd.to_datetime(df_54_25['fecha'])
df_54_25['año'] = df_54_25['fecha'].dt.year
df_54_25['trimestre'] = df_54_25['fecha'].dt.quarter
texto_fecha = df_54_25['año'].astype('string') + "Q" + df_54_25['trimestre'].astype('string')
df_54_25['periodo'] = texto_fecha

df_54_25 = df_54_25.set_index('fecha').sort_index()
df_54_25 = df_54_25.reset_index()

print(f'Información acerca de {df_54_25.attrs['nombre']}')
print(df_54_25.info())

Información acerca de df_54_25
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 862 entries, 0 to 861
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   fecha                                862 non-null    datetime64[ns]
 1   Estadísticas Generales. IPC. España  862 non-null    float64
 2   año                                  862 non-null    int32
 3   trimestre                            862 non-null    int32
 4   periodo                              862 non-null    string
dtypes: datetime64[ns](1), float64(1), int32(2), string(1)
memory usage: 27.1 KB
None

In [85]:
df_54_25.head()

       fecha  Estadísticas Generales. IPC. España   año  trimestre periodo
0 1954-03-01                                 1.79  1954          1  1954Q1
1 1954-04-01                                 1.79  1954          2  1954Q2
2 1954-05-01                                 1.79  1954          2  1954Q2
3 1954-06-01                                 1.78  1954          2  1954Q2
4 1954-07-01                                 1.78  1954          3  1954Q3

## Cambio de nombre a columnas

In [86]:
df_54_25.columns

Index(['fecha', 'Estadísticas Generales. IPC. España', 'año', 'trimestre',
       'periodo'],
      dtype='object')

In [87]:
df_54_25 = df_54_25.rename(columns={
    'Estadísticas Generales. IPC. España': 'IPC_2021'
})

In [88]:
df_54_25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 862 entries, 0 to 861
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   fecha      862 non-null    datetime64[ns]
 1   IPC_2021   862 non-null    float64
 2   año        862 non-null    int32
 3   trimestre  862 non-null    int32
 4   periodo    862 non-null    string
dtypes: datetime64[ns](1), float64(1), int32(2), string(1)
memory usage: 27.1 KB

# 3. Cálculo de factores de conversión e IPC en diferentes años base

In [89]:
# Años base para los conversores
fechas = [1986, 2001, 2025]

# Calcular la media anual del IPC para cada año base
ipc_medias_base = {}

for año in fechas:
    datos_año = df_54_25[df_54_25['año'] == año]['IPC_2021']

    if len(datos_año) == 0:
        print(f'Año {año}: sin datos en el dataset. No se puede calcular el conversor.')
        continue

    media = datos_año.mean()
    n_meses = len(datos_año)
    ipc_medias_base[año] = media
    completitud = 'año sin nulos' if n_meses == 12 else f'{n_meses}/12 meses disponibles'


    print(f'Año {año}: IPC medio (base 2021) = {media:.4f} ({completitud})')

Año 1986: IPC medio (base 2021) = 38.7300 (año sin nulos)
Año 2001: IPC medio (base 2021) = 73.8433 (año sin nulos)
Año 2025: IPC medio (base 2021) = 126.7675 (año sin nulos)

In [90]:
# Calcular columnas de conversores
for año, ipc_media in ipc_medias_base.items():
    col_name = f'conversor_{año}'
    df_54_25[col_name] = (ipc_media / df_54_25['IPC_2021'])
    col_ipc = f'IPC_{año}'
    df_54_25[col_ipc] = (1/df_54_25[col_name]) * 100

print()
print('Columnas :')
print(df_54_25.columns.tolist())

Columnas :
['fecha', 'IPC_2021', 'año', 'trimestre', 'periodo', 'conversor_1986', 'IPC_1986', 'conversor_2001', 'IPC_2001', 'conversor_2025', 'IPC_2025']

In [91]:
# Verificación del conversor_2025: en los meses de 20215debe ser ~ 1.0
check_2025 = df_54_25[df_54_25['año'] == 2025][['fecha', 'IPC_2021', 'IPC_2025', 'conversor_2025']]
print('Verificación conversor_2025 en meses de 2025 (debe ser ≈ 1.0):')
print(check_2025.to_string(index=False))
print(f'\nMedia conversor_2025 en 2025: {check_2025["conversor_2025"].mean():.6f} (debe ser ≈ 1.0)')

Verificación conversor_2025 en meses de 2025 (debe ser ≈ 1.0):
     fecha  IPC_2021   IPC_2025  conversor_2025
2025-01-01    124.97  98.582050        1.014383
2025-02-01    125.46  98.968584        1.010422
2025-03-01    125.53  99.023803        1.009858
2025-04-01    126.32  99.646992        1.003543
2025-05-01    126.41  99.717988        1.002828
2025-06-01    127.25 100.380618        0.996208
2025-07-01    127.15 100.301733        0.996992
2025-08-01    127.20 100.341176        0.996600
2025-09-01    126.84 100.057191        0.999428
2025-10-01    127.72 100.751376        0.992542
2025-11-01    127.96 100.940699        0.990681
2025-12-01    128.40 101.287791        0.987286

Media conversor_2025 en 2025: 1.000064 (debe ser ≈ 1.0)

In [92]:
check_2025 = df_54_25[df_54_25['año'] == 2025][['fecha', 'IPC_2021', 'IPC_2025', 'conversor_2025']]
print(check_2025.to_string(index=False))

     fecha  IPC_2021   IPC_2025  conversor_2025
2025-01-01    124.97  98.582050        1.014383
2025-02-01    125.46  98.968584        1.010422
2025-03-01    125.53  99.023803        1.009858
2025-04-01    126.32  99.646992        1.003543
2025-05-01    126.41  99.717988        1.002828
2025-06-01    127.25 100.380618        0.996208
2025-07-01    127.15 100.301733        0.996992
2025-08-01    127.20 100.341176        0.996600
2025-09-01    126.84 100.057191        0.999428
2025-10-01    127.72 100.751376        0.992542
2025-11-01    127.96 100.940699        0.990681
2025-12-01    128.40 101.287791        0.987286

In [93]:
# Verificación: tabla resumen de deflactores en fechas clave
fechas_clave = ['1975-01-01',
                '1986-01-01',
                '1986-12-01',
                '1999-01-01',
                '2001-01-01',
                '2001-12-01',
                '2008-01-01',
                '2021-01-01',
                '2021-12-01',
                '2025-01-01',
                '2025-12-01'
                ]


cols_deflactor = ['fecha', ] + [f'IPC_{año}' for año in ipc_medias_base.keys()]
df_check = df_54_25[df_54_25['fecha'].isin(pd.to_datetime(fechas_clave))][cols_deflactor]

print('Comparación del IPC en fechas clave en diferentes bases:')
print(df_check.to_string(index=False))

Comparación del IPC en fechas clave en diferentes bases:
     fecha   IPC_1986   IPC_2001   IPC_2025
1975-01-01  20.733282  10.874374   6.334431
1986-01-01  97.366383  51.067575  29.747372
1986-12-01 102.478699  53.748928  31.309287
1999-01-01 175.781048  92.195188  53.704617
2001-01-01 187.451588  98.316255  57.270199
2001-12-01 192.460625 100.943439  58.800560
2008-01-01 233.823909 122.638017  71.437869
2021-01-01 269.739220 141.475195  82.410713
2021-12-01 287.374129 150.724507  87.798529
2025-01-01 322.669765 169.236672  98.582050
2025-12-01 331.525949 173.881641 101.287791

In [94]:
df_54_25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 862 entries, 0 to 861
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fecha           862 non-null    datetime64[ns]
 1   IPC_2021        862 non-null    float64
 2   año             862 non-null    int32
 3   trimestre       862 non-null    int32
 4   periodo         862 non-null    string
 5   conversor_1986  862 non-null    float64
 6   IPC_1986        862 non-null    float64
 7   conversor_2001  862 non-null    float64
 8   IPC_2001        862 non-null    float64
 9   conversor_2025  862 non-null    float64
 10  IPC_2025        862 non-null    float64
dtypes: datetime64[ns](1), float64(7), int32(2), string(1)
memory usage: 67.5 KB

In [95]:
df_54_25 = df_54_25.filter(regex='^(?!conversor_)')
orden = ['fecha', 'año', 'trimestre', 'periodo'] + [columna for columna in df_54_25.columns if columna.startswith('IPC_')]
df_54_25 = df_54_25[orden]
df_54_25

,fecha,año,trimestre,periodo,IPC_2021,IPC_1986,IPC_2001,IPC_2025
0,1954-03-01,1954,1,1954Q1,1.79,4.621740,2.424051,1.412034
1,1954-04-01,1954,2,1954Q2,1.79,4.621740,2.424051,1.412034
2,1954-05-01,1954,2,1954Q2,1.79,4.621740,2.424051,1.412034
3,1954-06-01,1954,2,1954Q2,1.78,4.595920,2.410509,1.404145
4,1954-07-01,1954,3,1954Q3,1.78,4.595920,2.410509,1.404145
...,...,...,...,...,...,...,...,...
857,2025-08-01,2025,3,2025Q3,127.20,328.427576,172.256579,100.341176
858,2025-09-01,2025,3,2025Q3,126.84,327.498064,171.769061,100.057191
859,2025-10-01,2025,4,2025Q4,127.72,329.770204,172.960773,100.751376
860,2025-11-01,2025,4,2025Q4,127.96,330.389879,173.285785,100.940699
861,2025-12-01,2025,4,2025Q4,128.40,331.525949,173.881641,101.287791

In [96]:
px.line(df_54_25, x= 'fecha', y= 'IPC_2025', title= 'Evolución del IPC en base 2025 (IPC 2025 = 100)')

# 4. Guardando el dataset final en un archivo

In [97]:
# ── Recortar al rango de tasa de paro y guardar en Datasets ────────────
from pathlib import Path
FECHA_INICIO = '1974-07-01'
FECHA_FIN    = '2025-10-01'
ruta_datasets = Path(r'C:\Users\marco\PycharmProjects\TFM_Marcos\Datasets')

df_final = df_54_25.copy()


df_final = df_final[(df_final['fecha'] >= FECHA_INICIO) & (df_final['fecha'] <= FECHA_FIN)].copy()
df_final.to_csv(ruta_datasets / 'indice_precios_consumo_IPC_diferentes_bases.csv',
                index=False,
                encoding='utf-8-sig')

# 5. Información acerca del dataset final

In [98]:
df_final.attrs['nombre'] = 'df_final'
print('Información acerca del dataset final:')
print(f'{df_final.shape[0]} trimestres × {df_final.shape[1]} columnas | Rango: {df_final["fecha"].min().date()} → {df_final["fecha"].max().date()}')
columnas = df_final.columns.tolist()
print(f'  Columnas: {columnas}')
nulos = df_final.isna().sum()
nulos_col = nulos[nulos > 0]
if len(nulos_col) > 0:
    print(f'ALERTA  {df_final.attrs['nombre']}: nulos en {nulos_col.to_dict()}')
else:
    print(f'CORRECTO  {df_final.attrs['nombre']}: sin valores nulos')
print()

Información acerca del dataset final:
616 trimestres × 8 columnas | Rango: 1974-07-01 → 2025-10-01
  Columnas: ['fecha', 'año', 'trimestre', 'periodo', 'IPC_2021', 'IPC_1986', 'IPC_2001', 'IPC_2025']
CORRECTO  df_final: sin valores nulos

In [99]:
df_final.describe()

,fecha,año,trimestre,IPC_2021,IPC_1986,IPC_2001,IPC_2025
count,616,616.000000,616.000000,616.000000,616.000000,616.000000,616.000000
mean,2000-02-15 07:59:13.246753280,1999.665584,2.504870,68.259610,176.244798,92.438420,53.846302
min,1974-07-01 00:00:00,1974.000000,1.000000,7.290000,18.822618,9.872252,5.750685
25%,1987-04-23 12:00:00,1987.000000,2.000000,40.437500,104.408727,54.761206,31.898949
50%,2000-02-15 12:00:00,2000.000000,3.000000,70.280000,181.461399,95.174468,55.440077
75%,2012-12-08 18:00:00,2012.250000,3.250000,99.280000,256.338755,134.446802,78.316603
max,2025-10-01 00:00:00,2025.000000,4.000000,127.720000,329.770204,172.960773,100.751376
std,NaN,14.834431,1.117478,33.516929,86.539967,45.389242,26.439686

In [100]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 616 entries, 244 to 859
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   fecha      616 non-null    datetime64[ns]
 1   año        616 non-null    int32
 2   trimestre  616 non-null    int32
 3   periodo    616 non-null    string
 4   IPC_2021   616 non-null    float64
 5   IPC_1986   616 non-null    float64
 6   IPC_2001   616 non-null    float64
 7   IPC_2025   616 non-null    float64
dtypes: datetime64[ns](1), float64(4), int32(2), string(1)
memory usage: 38.5 KB