# LIMPIEZA DE DATOS — IPRI
### Índice de Precios Industriales, base 2021 (be2503)
### Incluye:
- Importación de librerías
- Carga de datasets (formato Boletín Estadístico BdE)
- Conversión de tipos y limpieza
- Exportación de archivos finales

---
**Fuentes (Banco de España, Boletín Estadístico):**
- `índice de Precios Industriales, base 2021, INE, be2503.csv`, *Índice de Precios Industriales. Base 2021.* Cobertura: enero 1975 – marzo 2026. Mensual.

# 0. Importación de "Librerías"

In [43]:
import pandas as pd

# 1. Carga de datasets

In [44]:
ruta = '../Fuentes/BDE/SB_OIP/'

### Serie de 1973 a 2026

In [45]:
df_75_26 = pd.read_csv(ruta + 'índice de Precios Industriales, base 2021, INE, be2503.csv', encoding= 'latin1', header=7)
df_75_26

,fecha,Estadísticas Generales. IPRI. Base 2021. Mercado interior. Total industria,Estadísticas generales. INE. IPRI. Mercado interior. Industrias extractivas. Base 2021. Índice. Mensual,Estadísticas generales. INE. IPRI. Mercado interior. Industria manufacturera. Base 2021. Índice. Mensual,"Estadísticas generales. INE. IPRI. Mercado interior. Suministro de energía eléctrica, gas, vapor y aire acondicionado. Base 2021. Índice. Mensual","Estadísticas generales. INE. IPRI. Mercado interior. Suministro de agua, actividades de saneamiento, gestión de residuos y descontaminación. Base 2021. Índice. Mensual",Estadísticas generales. INE. IPRI. Mercado interior. Energía. Base 2021. Índice. Mensual,Estadísticas generales. INE. IPRI. Mercado interior. Bienes de equipo. Base 2021. Índice. Mensual,Estadísticas generales. INE. IPRI. Mercado interior. Bienes intermedios. Base 2021. Índice. Mensual,Estadísticas generales. INE. IPRI. Mercado interior. Bienes de consumo. Base 2021. Índice. Mensual,Estadísticas generales. INE. IPRI. Mercado interior. Bienes de consumo duradero. Base 2021. Índice. Mensual,Estadísticas generales. INE. IPRI. Mercado interior. Bienes de consumo no duradero. Base 2021. Índice. Mensual
0,1/1/1975,10.80,11.34,11.84,6.03,NaN,6.04,11.87,13.00,12.04,13.45,11.76
1,2/1/1975,11.01,12.39,12.06,6.85,NaN,6.83,12.20,13.14,12.12,13.45,11.92
2,3/1/1975,11.08,12.56,12.06,6.89,NaN,6.89,12.37,13.14,12.20,13.45,11.92
3,4/1/1975,11.08,12.56,12.13,6.89,NaN,6.89,12.45,13.14,12.28,13.61,12.07
4,5/1/1975,11.21,12.72,12.28,6.89,NaN,6.89,12.53,13.14,12.44,13.78,12.23
...,...,...,...,...,...,...,...,...,...,...,...,...
610,11/1/2025,124.77,121.48,119.27,127.26,109.47,130.27,113.70,113.22,125.06,112.83,125.73
611,12/1/2025,125.23,121.32,118.42,133.30,109.61,131.75,113.85,113.46,124.90,112.98,125.56
612,1/1/2026,125.89,123.08,118.97,134.24,110.04,132.40,114.56,114.48,125.07,114.50,125.64
613,2/1/2026,122.13,124.44,119.81,113.53,110.31,119.26,114.73,115.12,125.22,114.58,125.79
614,3/1/2026,130.04,124.61,126.27,126.60,110.20,143.91,114.83,116.26,125.30,114.96,125.85

In [46]:
df_75_26.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 12 columns):
 #   Column                                                                                                                                                                    Non-Null Count  Dtype
---  ------                                                                                                                                                                    --------------  -----
 0   fecha                                                                                                                                                                     615 non-null    object
 1   Estadísticas Generales. IPRI. Base 2021. Mercado interior. Total industria                                                                                                615 non-null    float64
 2   Estadísticas generales. INE. IPRI.  Mercado interior. Industrias extractivas. Base 2021. Índice. Mensual                                                                  615 non-null    float64
 3   Estadísticas generales. INE. IPRI.  Mercado interior. Industria manufacturera. Base 2021. Índice. Mensual                                                                 615 non-null    float64
 4   Estadísticas generales. INE. IPRI.  Mercado interior. Suministro de energía eléctrica, gas, vapor y aire acondicionado. Base 2021. Índice. Mensual                        615 non-null    float64
 5   Estadísticas generales. INE. IPRI.  Mercado interior. Suministro de agua, actividades de saneamiento, gestión de residuos y descontaminación. Base 2021. Índice. Mensual  231 non-null    float64
 6   Estadísticas generales. INE. IPRI.  Mercado interior. Energía. Base 2021. Índice. Mensual                                                                                 615 non-null    float64
 7   Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de equipo. Base 2021. Índice. Mensual                                                                        615 non-null    float64
 8   Estadísticas generales. INE. IPRI.  Mercado interior. Bienes intermedios. Base 2021. Índice. Mensual                                                                      615 non-null    float64
 9   Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo. Base 2021. Índice. Mensual                                                                       615 non-null    float64
 10  Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo duradero. Base 2021. Índice. Mensual                                                              615 non-null    float64
 11  Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo no duradero. Base 2021. Índice. Mensual                                                           615 non-null    float64
dtypes: float64(11), object(1)
memory usage: 57.8+ KB

### Chequeo en conjunto

In [47]:
dataframes = [df_75_26]

df_75_26.attrs['nombre'] = 'df_75_26'

In [48]:
# Valores únicos de cada dataset para ver las categorías
for df in dataframes:
    print(f'Valores únicos en {df.attrs['nombre']}')
    for columna in df:
        print(df[columna].unique())

Valores únicos en df_75_26
['1/1/1975' '2/1/1975' '3/1/1975' '4/1/1975' '5/1/1975' '6/1/1975'
 '7/1/1975' '8/1/1975' '9/1/1975' '10/1/1975' '11/1/1975' '12/1/1975'
 '1/1/1976' '2/1/1976' '3/1/1976' '4/1/1976' '5/1/1976' '6/1/1976'
 '7/1/1976' '8/1/1976' '9/1/1976' '10/1/1976' '11/1/1976' '12/1/1976'
 '1/1/1977' '2/1/1977' '3/1/1977' '4/1/1977' '5/1/1977' '6/1/1977'
 '7/1/1977' '8/1/1977' '9/1/1977' '10/1/1977' '11/1/1977' '12/1/1977'
 '1/1/1978' '2/1/1978' '3/1/1978' '4/1/1978' '5/1/1978' '6/1/1978'
 '7/1/1978' '8/1/1978' '9/1/1978' '10/1/1978' '11/1/1978' '12/1/1978'
 '1/1/1979' '2/1/1979' '3/1/1979' '4/1/1979' '5/1/1979' '6/1/1979'
 '7/1/1979' '8/1/1979' '9/1/1979' '10/1/1979' '11/1/1979' '12/1/1979'
 '1/1/1980' '2/1/1980' '3/1/1980' '4/1/1980' '5/1/1980' '6/1/1980'
 '7/1/1980' '8/1/1980' '9/1/1980' '10/1/1980' '11/1/1980' '12/1/1980'
 '1/1/1981' '2/1/1981' '3/1/1981' '4/1/1981' '5/1/1981' '6/1/1981'
 '7/1/1981' '8/1/1981' '9/1/1981' '10/1/1981' '11/1/1981' '12/1/1981'
 '1/1/1982' '2/1/1982' '3/1/1982' '4/1/1982' '5/1/1982' '6/1/1982'
 '7/1/1982' '8/1/1982' '9/1/1982' '10/1/1982' '11/1/1982' '12/1/1982'
 '1/1/1983' '2/1/1983' '3/1/1983' '4/1/1983' '5/1/1983' '6/1/1983'
 '7/1/1983' '8/1/1983' '9/1/1983' '10/1/1983' '11/1/1983' '12/1/1983'
 '1/1/1984' '2/1/1984' '3/1/1984' '4/1/1984' '5/1/1984' '6/1/1984'
 '7/1/1984' '8/1/1984' '9/1/1984' '10/1/1984' '11/1/1984' '12/1/1984'
 '1/1/1985' '2/1/1985' '3/1/1985' '4/1/1985' '5/1/1985' '6/1/1985'
 '7/1/1985' '8/1/1985' '9/1/1985' '10/1/1985' '11/1/1985' '12/1/1985'
 '1/1/1986' '2/1/1986' '3/1/1986' '4/1/1986' '5/1/1986' '6/1/1986'
 '7/1/1986' '8/1/1986' '9/1/1986' '10/1/1986' '11/1/1986' '12/1/1986'
 '1/1/1987' '2/1/1987' '3/1/1987' '4/1/1987' '5/1/1987' '6/1/1987'
 '7/1/1987' '8/1/1987' '9/1/1987' '10/1/1987' '11/1/1987' '12/1/1987'
 '1/1/1988' '2/1/1988' '3/1/1988' '4/1/1988' '5/1/1988' '6/1/1988'
 '7/1/1988' '8/1/1988' '9/1/1988' '10/1/1988' '11/1/1988' '12/1/1988'
 '1/1/1989' '2/1/1989' '3/1/1989' '4/1/1989' '5/1/1989' '6/1/1989'
 '7/1/1989' '8/1/1989' '9/1/1989' '10/1/1989' '11/1/1989' '12/1/1989'
 '1/1/1990' '2/1/1990' '3/1/1990' '4/1/1990' '5/1/1990' '6/1/1990'
 '7/1/1990' '8/1/1990' '9/1/1990' '10/1/1990' '11/1/1990' '12/1/1990'
 '1/1/1991' '2/1/1991' '3/1/1991' '4/1/1991' '5/1/1991' '6/1/1991'
 '7/1/1991' '8/1/1991' '9/1/1991' '10/1/1991' '11/1/1991' '12/1/1991'
 '1/1/1992' '2/1/1992' '3/1/1992' '4/1/1992' '5/1/1992' '6/1/1992'
 '7/1/1992' '8/1/1992' '9/1/1992' '10/1/1992' '11/1/1992' '12/1/1992'
 '1/1/1993' '2/1/1993' '3/1/1993' '4/1/1993' '5/1/1993' '6/1/1993'
 '7/1/1993' '8/1/1993' '9/1/1993' '10/1/1993' '11/1/1993' '12/1/1993'
 '1/1/1994' '2/1/1994' '3/1/1994' '4/1/1994' '5/1/1994' '6/1/1994'
 '7/1/1994' '8/1/1994' '9/1/1994' '10/1/1994' '11/1/1994' '12/1/1994'
 '1/1/1995' '2/1/1995' '3/1/1995' '4/1/1995' '5/1/1995' '6/1/1995'
 '7/1/1995' '8/1/1995' '9/1/1995' '10/1/1995' '11/1/1995' '12/1/1995'
 '1/1/1996' '2/1/1996' '3/1/1996' '4/1/1996' '5/1/1996' '6/1/1996'
 '7/1/1996' '8/1/1996' '9/1/1996' '10/1/1996' '11/1/1996' '12/1/1996'
 '1/1/1997' '2/1/1997' '3/1/1997' '4/1/1997' '5/1/1997' '6/1/1997'
 '7/1/1997' '8/1/1997' '9/1/1997' '10/1/1997' '11/1/1997' '12/1/1997'
 '1/1/1998' '2/1/1998' '3/1/1998' '4/1/1998' '5/1/1998' '6/1/1998'
 '7/1/1998' '8/1/1998' '9/1/1998' '10/1/1998' '11/1/1998' '12/1/1998'
 '1/1/1999' '2/1/1999' '3/1/1999' '4/1/1999' '5/1/1999' '6/1/1999'
 '7/1/1999' '8/1/1999' '9/1/1999' '10/1/1999' '11/1/1999' '12/1/1999'
 '1/1/2000' '2/1/2000' '3/1/2000' '4/1/2000' '5/1/2000' '6/1/2000'
 '7/1/2000' '8/1/2000' '9/1/2000' '10/1/2000' '11/1/2000' '12/1/2000'
 '1/1/2001' '2/1/2001' '3/1/2001' '4/1/2001' '5/1/2001' '6/1/2001'
 '7/1/2001' '8/1/2001' '9/1/2001' '10/1/2001' '11/1/2001' '12/1/2001'
 '1/1/2002' '2/1/2002' '3/1/2002' '4/1/2002' '5/1/2002' '6/1/2002'
 '7/1/2002' '8/1/2002' '9/1/2002' '10/1/2002' '11/1/2002' '12/1/2002'
 '1/1/2003' '2/1/2003' '3/1/2003' '4/1/2003' '5/1/2003' '6/1/2003'
 '7/1/2003' '8/1/2003' '9/1/2003' '10/1/2003' '11/1/2003' '12/1/2003'
 '1/1/2004' '2/1/2004' '3/1/2004' '4/1/2004' '5/1/2004' '6/1/2004'
 '7/1/2004' '8/1/2004' '9/1/2004' '10/1/2004' '11/1/2004' '12/1/2004'
 '1/1/2005' '2/1/2005' '3/1/2005' '4/1/2005' '5/1/2005' '6/1/2005'
 '7/1/2005' '8/1/2005' '9/1/2005' '10/1/2005' '11/1/2005' '12/1/2005'
 '1/1/2006' '2/1/2006' '3/1/2006' '4/1/2006' '5/1/2006' '6/1/2006'
 '7/1/2006' '8/1/2006' '9/1/2006' '10/1/2006' '11/1/2006' '12/1/2006'
 '1/1/2007' '2/1/2007' '3/1/2007' '4/1/2007' '5/1/2007' '6/1/2007'
 '7/1/2007' '8/1/2007' '9/1/2007' '10/1/2007' '11/1/2007' '12/1/2007'
 '1/1/2008' '2/1/2008' '3/1/2008' '4/1/2008' '5/1/2008' '6/1/2008'
 '7/1/2008' '8/1/2008' '9/1/2008' '10/1/2008' '11/1/2008' '12/1/2008'
 '1/1/2009' '2/1/2009' '3/1/2009' '4/1/2009' '5/1/2009' '6/1/2009'
 '7/1/2009' '8/1/2009' '9/1/2009' '10/1/2009' '11/1/2009' '12/1/2009'
 '1/1/2010' '2/1/2010' '3/1/2010' '4/1/2010' '5/1/2010' '6/1/2010'
 '7/1/2010' '8/1/2010' '9/1/2010' '10/1/2010' '11/1/2010' '12/1/2010'
 '1/1/2011' '2/1/2011' '3/1/2011' '4/1/2011' '5/1/2011' '6/1/2011'
 '7/1/2011' '8/1/2011' '9/1/2011' '10/1/2011' '11/1/2011' '12/1/2011'
 '1/1/2012' '2/1/2012' '3/1/2012' '4/1/2012' '5/1/2012' '6/1/2012'
 '7/1/2012' '8/1/2012' '9/1/2012' '10/1/2012' '11/1/2012' '12/1/2012'
 '1/1/2013' '2/1/2013' '3/1/2013' '4/1/2013' '5/1/2013' '6/1/2013'
 '7/1/2013' '8/1/2013' '9/1/2013' '10/1/2013' '11/1/2013' '12/1/2013'
 '1/1/2014' '2/1/2014' '3/1/2014' '4/1/2014' '5/1/2014' '6/1/2014'
 '7/1/2014' '8/1/2014' '9/1/2014' '10/1/2014' '11/1/2014' '12/1/2014'
 '1/1/2015' '2/1/2015' '3/1/2015' '4/1/2015' '5/1/2015' '6/1/2015'
 '7/1/2015' '8/1/2015' '9/1/2015' '10/1/2015' '11/1/2015' '12/1/2015'
 '1/1/2016' '2/1/2016' '3/1/2016' '4/1/2016' '5/1/2016' '6/1/2016'
 '7/1/2016' '8/1/2016' '9/1/2016' '10/1/2016' '11/1/2016' '12/1/2016'
 '1/1/2017' '2/1/2017' '3/1/2017' '4/1/2017' '5/1/2017' '6/1/2017'
 '7/1/2017' '8/1/2017' '9/1/2017' '10/1/2017' '11/1/2017' '12/1/2017'
 '1/1/2018' '2/1/2018' '3/1/2018' '4/1/2018' '5/1/2018' '6/1/2018'
 '7/1/2018' '8/1/2018' '9/1/2018' '10/1/2018' '11/1/2018' '12/1/2018'
 '1/1/2019' '2/1/2019' '3/1/2019' '4/1/2019' '5/1/2019' '6/1/2019'
 '7/1/2019' '8/1/2019' '9/1/2019' '10/1/2019' '11/1/2019' '12/1/2019'
 '1/1/2020' '2/1/2020' '3/1/2020' '4/1/2020' '5/1/2020' '6/1/2020'
 '7/1/2020' '8/1/2020' '9/1/2020' '10/1/2020' '11/1/2020' '12/1/2020'
 '1/1/2021' '2/1/2021' '3/1/2021' '4/1/2021' '5/1/2021' '6/1/2021'
 '7/1/2021' '8/1/2021' '9/1/2021' '10/1/2021' '11/1/2021' '12/1/2021'
 '1/1/2022' '2/1/2022' '3/1/2022' '4/1/2022' '5/1/2022' '6/1/2022'
 '7/1/2022' '8/1/2022' '9/1/2022' '10/1/2022' '11/1/2022' '12/1/2022'
 '1/1/2023' '2/1/2023' '3/1/2023' '4/1/2023' '5/1/2023' '6/1/2023'
 '7/1/2023' '8/1/2023' '9/1/2023' '10/1/2023' '11/1/2023' '12/1/2023'
 '1/1/2024' '2/1/2024' '3/1/2024' '4/1/2024' '5/1/2024' '6/1/2024'
 '7/1/2024' '8/1/2024' '9/1/2024' '10/1/2024' '11/1/2024' '12/1/2024'
 '1/1/2025' '2/1/2025' '3/1/2025' '4/1/2025' '5/1/2025' '6/1/2025'
 '7/1/2025' '8/1/2025' '9/1/2025' '10/1/2025' '11/1/2025' '12/1/2025'
 '1/1/2026' '2/1/2026' '3/1/2026']
[ 10.8   11.01  11.08  11.21  11.28  11.35  11.42  11.62  11.76  11.9
  12.1   12.45  12.65  12.79  12.92  12.99  13.2   13.33  13.68  13.88
  14.36  14.77  14.91  15.04  15.32  15.8   16.07  16.34  16.55  16.62
  16.82  16.96  17.1   17.3   17.64  17.85  17.98  18.05  18.19  18.39
  18.53  18.6   19.01  19.28  19.42  19.63  19.76  20.1   20.51  20.86
  21.2   21.4   21.47  21.68  22.16  23.11  23.32  23.39  23.52  23.66
  24.07  24.34  24.62  24.82  24.96  25.16  25.92  26.19  26.39  27.35
  27.49  27.76  27.97  28.38  28.58  28.79  29.06  29.2   29.68  30.22
  30.5   30.7   30.98  31.11  31.25  31.39  31.59  31.87  32.14  33.03
  33.71  34.26  34.46  34.81  35.01  35.35  35.63  35.9   36.17  36.79
  37.06  37.75  38.22  38.91  39.18  39.59  39.8   40.    40.14  40.28
  40.41  40.69  40.89  41.03  41.99  42.46  42.6   42.81  43.08  43.22
  43.42  43.49  43.69  43.83  43.56  43.63  43.35  43.76  43.97  44.11
  44.04  44.17  44.24  44.38  44.52  44.65  44.72  44.99  44.86  45.06
  45.27  45.34  45.47  45.61  45.81  45.88  46.22  46.57  46.7   46.77
  46.84  46.91  47.18  47.32  47.39  47.46  47.52  47.8   47.93  47.73
  48.34  48.69  48.62  48.89  48.82  48.75  48.96  49.23  49.3   49.44
  49.51  49.58  49.64  50.05  50.12  50.19  50.26  50.33  50.46  50.67
  50.94  51.01  51.15  51.22  51.35  51.9   52.11  52.24  52.31  52.45
  52.65  52.79  52.93  53.13  53.4   53.75  54.02  54.91  55.52  55.93
  56.14  56.28  56.35  56.41  56.48  56.69  56.62  56.96  57.1   57.03
  57.17  57.3   57.37  57.44  57.51  57.64  57.85  57.99  58.05  57.92
  57.78  57.58  57.23  56.82  56.76  57.71  58.46  58.6   58.81  59.22
  59.7   60.11  60.24  60.52  60.72  60.86  60.99  61.61  61.95  61.75
  61.88  62.02  62.16  62.09  61.41  61.27  61.68  62.29  62.43  62.23
  62.36  62.57  62.7   63.11  63.39  63.73  63.18  62.84  62.77  62.91
  63.05  63.52  63.87  64.35  64.82  65.23  65.51  65.78  66.05  66.47
  66.4   66.19  66.6   67.01  67.49  67.9   67.83  68.04  68.38  68.86
  69.41  69.68  69.61  70.64  71.18  71.39  71.8   72.28  72.41  72.82
  72.89  72.48  72.21  73.23  73.71  74.12  74.47  74.6   74.74  74.88
  75.08  75.63  76.11  76.38  77.41  77.88  78.57  79.05  80.    80.89
  82.33  81.78  81.3   80.28  78.29  76.65  77.    76.59  76.45  76.93
  76.79  77.27  76.86  77.68  77.84  78.52  79.51  79.74  79.81  79.73
  79.95  80.11  80.41  80.85  81.79  83.37  84.18  84.84  85.31  85.1
  85.13  85.79  85.46  85.62  85.75  85.86  85.87  87.39  88.04  88.64
  87.97  87.41  88.28  89.37  89.3   89.12  88.65  88.67  89.72  89.93
  88.59  87.52  88.54  88.57  89.38  89.28  89.43  88.97  88.21  89.21
  88.    87.12  87.25  87.36  88.1   88.85  88.9   88.13  88.63  87.9
  86.89  85.97  85.56  85.76  86.15  86.55  86.85  87.63  87.72  86.2
  85.42  84.77  84.64  84.06  81.93  81.04  81.49  81.37  82.02  83.67
  83.68  83.46  83.73  84.99  85.14  86.5   87.05  86.19  86.27  86.33
  86.32  86.23  86.18  86.69  87.37  87.82  87.99  88.14  87.85  89.81
  90.25  90.62  91.33  91.37  90.4   89.49  89.63  89.97  90.01  89.05
  89.66  88.26  88.33  88.78  88.27  87.94  88.77  87.62  84.97  82.41
  82.1   83.77  85.29  85.45  85.05  85.85  86.66  89.62  90.41  93.12
  94.59  96.7   98.59 100.38 105.78 112.08 113.5  117.15 121.93 124.55
 132.88 134.58 135.85 138.85 139.64 143.47 143.41 140.06 136.79 134.56
 131.47 134.47 131.06 128.55 126.66 127.81 127.57 129.2  131.2  129.31
 126.46 126.12 126.33 123.01 120.27 119.92 121.   123.7  125.58 127.38
 124.37 124.33 127.92 129.06 129.57 131.24 125.82 121.85 120.9  124.89
 126.05 125.3  124.67 125.34 124.77 125.23 125.89 122.13 130.04]
[ 11.34  12.39  12.56  12.72  12.8   12.88  13.04  13.12  13.85  14.82
  15.07  15.15  15.23  15.31  15.47  16.2   17.5   18.31  18.39  20.49
  20.74  21.14  21.22  21.3   21.87  21.95  22.11  22.68  23.    24.14
  24.38  24.46  25.19  25.27  25.43  25.6   28.27  28.11  28.75  29.08
  29.89  30.37  30.62  30.7   30.78  30.86  34.67  35.15  35.48  35.56
  36.37  36.45  36.61  36.69  37.18  38.64  39.2   39.28  39.61  40.01
  43.82  43.98  44.23  44.87  44.79  45.2   45.6   45.52  45.44  46.01
  46.25  47.95  48.6   49.57  49.17  49.98  50.7   50.62  52.97  53.7
  54.27  54.67  55.24  55.08  55.    55.16  55.81  56.05  56.21  57.75
  57.99  57.91  57.83  58.24  58.8   59.05  58.97  58.89  59.13  59.29
  59.61  59.53  60.1   59.78  59.45  60.34  60.51  60.26  60.42  60.83
  60.91  60.67  61.4   61.15  61.48  61.56  62.13  62.37  62.85  63.02
  62.94  61.64  62.69  63.18  63.75  64.15  63.66  63.83  63.26  63.34
  63.5   65.45  65.61  65.77  65.93  66.09  65.85  65.37  66.01  66.58
  66.9   66.82  67.07  66.74  67.47  67.8   67.88  68.04  68.12  68.52
  68.44  68.61  69.01  69.5   69.98  70.06  69.66  69.82  70.31  70.23
  69.9   69.58  70.47  70.39  70.55  70.71  70.95  70.63  71.04  69.42
  69.25  69.17  68.85  69.09  68.93  68.2   67.55  68.28  69.33  71.93
  72.74  73.14  73.22  72.98  73.55  74.11  74.28  73.87  74.44  74.92
  75.    75.25  75.17  75.98  75.65  75.33  74.36  74.03  74.68  75.73
  75.57  74.6   74.84  74.52  76.14  76.46  76.79  77.35  77.52  77.76
  78.08  77.6   78.16  78.73  78.65  79.86  80.35  80.59  80.51  81.16
  81.97  81.4   81.65  81.73  80.92  83.67  83.83  83.75  84.08  84.4
  84.48  84.32  85.05  87.07  88.21  88.13  88.37  89.26  88.77  89.58
  89.83  89.18  92.01  92.66  92.9   93.39  94.04  94.12  94.36  94.2
  93.55  94.28  94.44  94.77  94.85  95.5   95.09  94.52  94.69  95.42
  94.91  94.86  94.75  94.38  94.47  94.4   95.22  94.72  95.73  96.82
  96.65  96.78  96.37  95.98  96.36  95.83  95.96  96.84  96.41  96.71
  97.05  96.48  96.47  97.79  97.26  97.52  97.33  97.58  97.23  97.62
  97.11  97.17  96.7   97.14  98.56  97.78  97.82  97.53  97.07  97.89
  98.08  97.84  97.69  97.61  97.65  97.68  98.05  97.81  98.66  98.11
  97.72  97.16  97.56  97.99  97.49  97.48  97.92  97.41  97.09  97.01
  97.08  96.85  96.31  96.22  95.99  96.67  96.75  95.38  95.18  95.12
  95.54  95.6   95.57  95.07  95.15  95.49  95.88  95.53  95.74  96.01
  96.23  96.53  96.21  96.26  96.11  96.96  97.22  97.2   97.31  97.21
  96.99  97.24  97.38  97.45  97.57  98.01  97.6   97.66  97.75  97.54
  98.21  98.02  97.88  97.94  97.8   99.06  99.    99.13  99.23  99.36
  98.8   99.08  99.18  98.96  99.1   99.43  99.19  99.45  99.69  99.89
  99.67  99.63 100.27  99.88  99.87  99.96 100.24 100.59 100.86 103.55
 104.89 104.59 106.81 107.4  107.85 108.6  108.73 109.9  110.11 110.17
 112.01 114.07 114.69 114.65 114.62 114.92 115.5  115.71 115.61 114.74
 114.4  114.55 114.76 115.76 116.42 116.36 116.26 116.61 115.9  115.81
 115.53 115.98 115.97 116.11 117.72 119.8  121.04 120.97 121.01 121.07
 120.93 121.32 121.42 121.48 123.08 124.44 124.61]
[ 11.84  12.06  12.13  12.28  12.36  12.43  12.51  12.66  12.73  12.96
  13.18  13.56  13.71  13.93  14.08  14.16  14.23  14.46  14.53  14.98
  15.21  15.66  16.1   16.25  16.4   16.7   17.23  17.53  17.9   18.05
  18.2   18.43  18.58  18.73  18.95  19.33  19.63  19.7   19.85  19.92
  20.22  20.3   20.45  20.82  21.2   21.42  21.65  21.8   22.17  22.55
  22.92  23.22  23.52  23.6   23.82  24.34  25.32  25.62  25.77  25.92
  26.44  26.59  26.89  27.19  27.27  27.57  28.31  28.54  28.76  29.74
  29.96  30.26  30.49  31.01  31.16  31.54  31.76  31.91  32.43  32.96
  33.26  33.48  33.78  33.86  34.08  34.31  34.46  34.83  35.13  36.1
  36.78  37.38  37.68  38.05  38.35  38.73  38.95  39.25  39.62  40.07
  40.37  41.2   41.72  42.55  42.85  43.07  43.37  43.52  43.74  43.82
  44.04  44.34  44.49  44.72  45.84  46.14  46.37  46.59  46.82  46.89
  47.04  47.26  47.41  47.56  47.79  47.71  47.49  47.12  47.34  46.97
  47.64  47.94  48.16  48.24  48.31  48.61  48.46  48.91  48.99  49.14
  49.29  49.51  49.59  49.96  50.34  50.49  50.56  50.64  50.71  51.08
  51.16  51.23  51.38  51.61  51.68  51.46  51.76  52.21  52.58  52.51
  52.73  52.36  52.43  52.66  52.96  53.03  53.11  53.18  53.26  53.41
  53.71  53.86  53.93  54.08  54.23  54.46  54.76  54.91  55.05  55.13
  55.2   55.8   56.03  56.18  56.25  56.48  56.7   56.85  57.    57.23
  57.53  57.98  58.28  59.25  60.    60.45  60.67  60.9   60.97  61.05
  61.12  61.35  61.2   61.65  61.8   61.72  61.87  61.57  62.02  62.1
  62.17  62.32  62.25  62.4   62.55  62.77  62.92  62.99  62.84  62.7
  62.62  62.47  61.95  63.29  63.67  63.82  63.89  64.19  64.64  65.17
  65.69  65.84  66.14  66.37  66.52  66.66  67.41  67.79  67.71  67.49
  67.26  67.64  67.86  67.94  67.11  66.89  67.19  67.34  68.16  68.24
  68.01  68.39  68.46  68.09  68.84  69.21  69.66  68.99  68.61  68.54
  68.76  68.91  69.06  69.36  69.81  70.41  71.01  71.53  71.83  72.13
  72.43  72.88  72.73  72.58  73.41  74.01  74.53  74.38  74.6   75.05
  75.5   76.1   76.4   76.03  76.93  77.68  77.9   78.42  79.02  79.17
  79.55  79.62  79.1   78.8   78.72  80.15  80.75  81.12  81.27  81.5
  81.57  81.87  82.47  83.14  83.44  84.27  84.87  85.69  86.29  87.49
  88.61  89.29  88.54  87.94  86.36  83.82  81.65  81.42  81.35  80.82
  80.97  81.05  82.17  81.8   82.54  82.72  83.59  84.76  85.12  84.72
  85.08  85.45  85.52  86.09  87.2   88.39  89.41  90.26  90.82  90.51
  90.56  90.84  90.5   90.73  90.61  90.74  90.54  91.38  91.98  92.85
  93.01  92.51  91.69  92.33  93.55  93.99  93.73  93.18  93.35  93.92
  93.57  92.81  92.65  92.47  92.74  92.79  92.72  92.15  91.87  91.79
  91.75  91.66  91.53  92.    91.86  91.23  90.68  89.33  88.34  89.44
  90.08  90.57  91.06  91.    90.6   89.56  88.99  88.43  88.17  87.18
  86.24  85.72  86.51  86.95  87.73  88.57  88.31  88.19  88.25  88.96
  88.85  89.99  90.94  91.3   91.19  91.18  91.09  90.63  90.67  90.9
  91.33  91.56  91.89  92.11  92.36  93.28  93.96  94.16  94.01  94.09
  94.29  94.8   92.56  92.44  93.16  93.76  94.42  94.66  93.56  93.82
  92.7   93.43  93.4   93.3   93.52  94.02  93.38  91.12  89.19  88.64
  89.52  90.43  90.47  90.17  90.4   91.68  94.85  96.61  97.53  99.04
  99.7  100.79 100.84 101.89 104.09 105.68 105.8  108.26 110.78 116.81
 120.18 122.22 125.13 123.74 121.89 121.81 123.48 122.56 120.16 121.76
 121.55 121.51 120.66 119.32 119.27 119.42 121.21 122.45 121.63 120.55
 119.68 120.28 121.3  121.42 121.56 120.91 120.8  120.79 119.84 118.76
 119.02 118.69 118.51 119.77 120.08 119.36 118.35 118.07 118.34 119.
 118.55 118.79 118.42 118.97 119.81 126.27]
[  6.03   6.85   6.89   8.03   8.17   8.22   9.36   9.9    9.95  11.27
  11.37  11.41  13.28  13.33  15.06  15.2   16.16  17.39  17.44  19.4
  19.44  20.45  20.54  20.58  24.14  26.2   26.24  28.21  28.25  31.49
  31.45  31.4   33.14  33.23  34.64  34.6   35.83  35.87  37.65  37.7
  39.85  40.3   40.48  41.58  41.63  42.68  42.63  42.72  43.45  43.59
  43.5   43.54  44.18  44.32  44.36  44.27  44.23  44.41  44.46  43.18
  43.22  43.36  43.41  42.08  41.85  41.72  41.67  41.49  41.12  41.08
  40.53  40.62  40.58  40.71  40.99  41.4   41.17  41.21  41.44  41.9
  41.95  42.17  42.13  41.76  42.26  42.54  42.58  43.09  43.13  43.63
  42.86  42.9   42.95  42.99  44.04  44.55  44.59  44.77  45.    45.05
  46.01  46.05  46.19  47.92  47.88  49.07  49.84  49.89  51.8   51.48
  51.89  52.21  54.04  54.27  59.61  59.33  61.02  60.93  61.25  63.94
  64.04  64.22  62.26  62.12  62.44  62.62  61.75  61.39  61.16  61.07
  61.43  62.53  62.68  62.72  63.14  62.89  63.22  64.46  64.13  63.44
  64.71  64.65  65.03  68.46  68.56  68.54  68.74  68.89  68.83  71.15
  70.75  70.7   71.87  71.88  72.74  77.24  78.1   77.71  73.92  75.54
  75.95  77.91  78.7   76.52  76.61  76.32  77.76  81.12  79.89  74.32
  71.72  77.6   78.47  81.55  80.89  81.96  81.79  78.98  84.45  77.93
  73.43  74.57  74.53  78.35  81.52  81.67  78.03  80.81  79.53  76.29
  77.07  78.9   75.48  74.92  75.03  74.58  78.97  81.06  77.32  75.52
  74.42  74.82  75.78  68.32  65.67  64.81  62.39  67.94  69.06  68.44
  69.65  73.44  74.68  77.16  81.76  74.7   70.58  71.03  71.75  73.55
  72.95  72.7   75.33  76.33  76.36  74.84  76.17  72.12  72.3   77.62
  79.83  81.07  83.32  81.98  80.46  81.02  81.92  79.72  76.8   77.31
  76.75  76.1   77.82  75.41  73.51  73.67  71.59  73.37  70.74  66.89
  62.46  62.78  66.64  69.92  69.25  71.21  69.08  71.19  71.7   78.92
  68.37  72.36  80.27  88.08  92.36  99.12 117.09 135.29 136.29 150.08
 165.86 168.69 187.68 180.84 178.19 181.31 192.85 224.66 224.65 196.5
 181.86 180.64 155.85 173.52 154.69 144.57 140.26 146.91 144.86 145.65
 151.02 144.26 133.42 135.55 134.23 114.61 101.13  98.93 106.45 119.65
 128.59 140.64 130.39 129.23 147.48 153.52 150.63 157.89 132.55 116.05
 112.25 131.97 135.16 133.23 128.83 133.33 127.26 133.3  134.24 113.53
 126.6 ]
[   nan  73.87  73.94  74.    74.07  74.14  74.28  74.49  76.36  76.92
  77.06  77.33  77.54  77.89  78.03  78.1   78.3   78.37  78.44  80.87
  81.08  81.56  82.05  82.26  82.33  82.19  82.4   82.6   83.71  83.74
  83.82  83.94  84.57  84.47  84.43  84.39  84.5   84.64  84.79  84.8
  85.82  85.97  86.53  86.73  86.86  86.87  86.92  86.74  86.68  86.61

In [49]:
# Información acerca del tipo de dato y valores nulos de las columnas de cada dataset
for df in dataframes:
    print(f'Información acerca de {df.attrs['nombre']}')
    print(df.info())

Información acerca de df_75_26
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 12 columns):
 #   Column                                                                                                                                                                    Non-Null Count  Dtype
---  ------                                                                                                                                                                    --------------  -----
 0   fecha                                                                                                                                                                     615 non-null    object
 1   Estadísticas Generales. IPRI. Base 2021. Mercado interior. Total industria                                                                                                615 non-null    float64
 2   Estadísticas generales. INE. IPRI.  Mercado interior. Industrias extractivas. Base 2021. Índice. Mensual                                                                  615 non-null    float64
 3   Estadísticas generales. INE. IPRI.  Mercado interior. Industria manufacturera. Base 2021. Índice. Mensual                                                                 615 non-null    float64
 4   Estadísticas generales. INE. IPRI.  Mercado interior. Suministro de energía eléctrica, gas, vapor y aire acondicionado. Base 2021. Índice. Mensual                        615 non-null    float64
 5   Estadísticas generales. INE. IPRI.  Mercado interior. Suministro de agua, actividades de saneamiento, gestión de residuos y descontaminación. Base 2021. Índice. Mensual  231 non-null    float64
 6   Estadísticas generales. INE. IPRI.  Mercado interior. Energía. Base 2021. Índice. Mensual                                                                                 615 non-null    float64
 7   Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de equipo. Base 2021. Índice. Mensual                                                                        615 non-null    float64
 8   Estadísticas generales. INE. IPRI.  Mercado interior. Bienes intermedios. Base 2021. Índice. Mensual                                                                      615 non-null    float64
 9   Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo. Base 2021. Índice. Mensual                                                                       615 non-null    float64
 10  Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo duradero. Base 2021. Índice. Mensual                                                              615 non-null    float64
 11  Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo no duradero. Base 2021. Índice. Mensual                                                           615 non-null    float64
dtypes: float64(11), object(1)
memory usage: 57.8+ KB
None

# 2. Limpieza

### Transformación de los datos de fecha

In [50]:
df_75_26['fecha'] = pd.to_datetime(df_75_26['fecha'])
df_75_26['año'] = df_75_26['fecha'].dt.year
df_75_26['trimestre'] = df_75_26['fecha'].dt.quarter
df_75_26['periodo'] = df_75_26['año'].astype(str) + 'Q' + df_75_26['trimestre'].astype(str)

df_75_26 = df_75_26.set_index('fecha').sort_index()
df_75_26 = df_75_26.reset_index()

print(f'Información acerca de {df_75_26.attrs['nombre']}')
print(df_75_26.info())

Información acerca de df_75_26
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 15 columns):
 #   Column                                                                                                                                                                    Non-Null Count  Dtype
---  ------                                                                                                                                                                    --------------  -----
 0   fecha                                                                                                                                                                     615 non-null    datetime64[ns]
 1   Estadísticas Generales. IPRI. Base 2021. Mercado interior. Total industria                                                                                                615 non-null    float64
 2   Estadísticas generales. INE. IPRI.  Mercado interior. Industrias extractivas. Base 2021. Índice. Mensual                                                                  615 non-null    float64
 3   Estadísticas generales. INE. IPRI.  Mercado interior. Industria manufacturera. Base 2021. Índice. Mensual                                                                 615 non-null    float64
 4   Estadísticas generales. INE. IPRI.  Mercado interior. Suministro de energía eléctrica, gas, vapor y aire acondicionado. Base 2021. Índice. Mensual                        615 non-null    float64
 5   Estadísticas generales. INE. IPRI.  Mercado interior. Suministro de agua, actividades de saneamiento, gestión de residuos y descontaminación. Base 2021. Índice. Mensual  231 non-null    float64
 6   Estadísticas generales. INE. IPRI.  Mercado interior. Energía. Base 2021. Índice. Mensual                                                                                 615 non-null    float64
 7   Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de equipo. Base 2021. Índice. Mensual                                                                        615 non-null    float64
 8   Estadísticas generales. INE. IPRI.  Mercado interior. Bienes intermedios. Base 2021. Índice. Mensual                                                                      615 non-null    float64
 9   Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo. Base 2021. Índice. Mensual                                                                       615 non-null    float64
 10  Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo duradero. Base 2021. Índice. Mensual                                                              615 non-null    float64
 11  Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo no duradero. Base 2021. Índice. Mensual                                                           615 non-null    float64
 12  año                                                                                                                                                                       615 non-null    int32
 13  trimestre                                                                                                                                                                 615 non-null    int32
 14  periodo                                                                                                                                                                   615 non-null    object
dtypes: datetime64[ns](1), float64(11), int32(2), object(1)
memory usage: 67.4+ KB
None

In [51]:
df_75_26.head()

,fecha,Estadísticas Generales. IPRI. Base 2021. Mercado interior. Total industria,Estadísticas generales. INE. IPRI. Mercado interior. Industrias extractivas. Base 2021. Índice. Mensual,Estadísticas generales. INE. IPRI. Mercado interior. Industria manufacturera. Base 2021. Índice. Mensual,"Estadísticas generales. INE. IPRI. Mercado interior. Suministro de energía eléctrica, gas, vapor y aire acondicionado. Base 2021. Índice. Mensual","Estadísticas generales. INE. IPRI. Mercado interior. Suministro de agua, actividades de saneamiento, gestión de residuos y descontaminación. Base 2021. Índice. Mensual",Estadísticas generales. INE. IPRI. Mercado interior. Energía. Base 2021. Índice. Mensual,Estadísticas generales. INE. IPRI. Mercado interior. Bienes de equipo. Base 2021. Índice. Mensual,Estadísticas generales. INE. IPRI. Mercado interior. Bienes intermedios. Base 2021. Índice. Mensual,Estadísticas generales. INE. IPRI. Mercado interior. Bienes de consumo. Base 2021. Índice. Mensual,Estadísticas generales. INE. IPRI. Mercado interior. Bienes de consumo duradero. Base 2021. Índice. Mensual,Estadísticas generales. INE. IPRI. Mercado interior. Bienes de consumo no duradero. Base 2021. Índice. Mensual,año,trimestre,periodo
0,1975-01-01,10.80,11.34,11.84,6.03,NaN,6.04,11.87,13.00,12.04,13.45,11.76,1975,1,1975Q1
1,1975-02-01,11.01,12.39,12.06,6.85,NaN,6.83,12.20,13.14,12.12,13.45,11.92,1975,1,1975Q1
2,1975-03-01,11.08,12.56,12.06,6.89,NaN,6.89,12.37,13.14,12.20,13.45,11.92,1975,1,1975Q1
3,1975-04-01,11.08,12.56,12.13,6.89,NaN,6.89,12.45,13.14,12.28,13.61,12.07,1975,2,1975Q2
4,1975-05-01,11.21,12.72,12.28,6.89,NaN,6.89,12.53,13.14,12.44,13.78,12.23,1975,2,1975Q2

## Cambio de nombre a columnas

In [52]:
df_75_26.columns

Index(['fecha',
       'Estadísticas Generales. IPRI. Base 2021. Mercado interior. Total industria',
       'Estadísticas generales. INE. IPRI.  Mercado interior. Industrias extractivas. Base 2021. Índice. Mensual',
       'Estadísticas generales. INE. IPRI.  Mercado interior. Industria manufacturera. Base 2021. Índice. Mensual',
       'Estadísticas generales. INE. IPRI.  Mercado interior. Suministro de energía eléctrica, gas, vapor y aire acondicionado. Base 2021. Índice. Mensual',
       'Estadísticas generales. INE. IPRI.  Mercado interior. Suministro de agua, actividades de saneamiento, gestión de residuos y descontaminación. Base 2021. Índice. Mensual',
       'Estadísticas generales. INE. IPRI.  Mercado interior. Energía. Base 2021. Índice. Mensual',
       'Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de equipo. Base 2021. Índice. Mensual',
       'Estadísticas generales. INE. IPRI.  Mercado interior. Bienes intermedios. Base 2021. Índice. Mensual',
       'Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo. Base 2021. Índice. Mensual',
       'Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo duradero. Base 2021. Índice. Mensual',
       'Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo no duradero. Base 2021. Índice. Mensual',
       'año', 'trimestre', 'periodo'],
      dtype='object')

In [53]:
df_75_26 = df_75_26.rename(columns={
    'Estadísticas Generales. IPRI. Base 2021. Mercado interior. Total industria': 'IPRI_total_industria_2021',
    'Estadísticas generales. INE. IPRI.  Mercado interior. Industrias extractivas. Base 2021. Índice. Mensual': 'IPRI_industrias_extractivas_2021',
    'Estadísticas generales. INE. IPRI.  Mercado interior. Industria manufacturera. Base 2021. Índice. Mensual': 'IPRI_industria_manufacturera_2021',
    'Estadísticas generales. INE. IPRI.  Mercado interior. Suministro de energía eléctrica, gas, vapor y aire acondicionado. Base 2021. Índice. Mensual': 'IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2021',
    'Estadísticas generales. INE. IPRI.  Mercado interior. Suministro de agua, actividades de saneamiento, gestión de residuos y descontaminación. Base 2021. Índice. Mensual': 'IPRI_suministro_agua_actividades_saneamiento_gestion_residuos_descontaminacion_2021',
    'Estadísticas generales. INE. IPRI.  Mercado interior. Energía. Base 2021. Índice. Mensual': 'IPRI_energia_2021',
    'Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de equipo. Base 2021. Índice. Mensual': 'IPRI_bienes_equipo_2021',
    'Estadísticas generales. INE. IPRI.  Mercado interior. Bienes intermedios. Base 2021. Índice. Mensual': 'IPRI_bienes_intermedios_2021',
    'Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo. Base 2021. Índice. Mensual': 'IPRI_bienes_consumo_2021',
    'Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo duradero. Base 2021. Índice. Mensual': 'IPRI_bienes_consumo_duradero_2021',
    'Estadísticas generales. INE. IPRI.  Mercado interior. Bienes de consumo no duradero. Base 2021. Índice. Mensual': 'IPRI_bienes_consumo_no_duradero_2021'
})

In [54]:
df_75_26.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 15 columns):
 #   Column                                                                               Non-Null Count  Dtype
---  ------                                                                               --------------  -----
 0   fecha                                                                                615 non-null    datetime64[ns]
 1   IPRI_total_industria_2021                                                            615 non-null    float64
 2   IPRI_industrias_extractivas_2021                                                     615 non-null    float64
 3   IPRI_industria_manufacturera_2021                                                    615 non-null    float64
 4   IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2021                  615 non-null    float64
 5   IPRI_suministro_agua_actividades_saneamiento_gestion_residuos_descontaminacion_2021  231 non-null    float64
 6   IPRI_energia_2021                                                                    615 non-null    float64
 7   IPRI_bienes_equipo_2021                                                              615 non-null    float64
 8   IPRI_bienes_intermedios_2021                                                         615 non-null    float64
 9   IPRI_bienes_consumo_2021                                                             615 non-null    float64
 10  IPRI_bienes_consumo_duradero_2021                                                    615 non-null    float64
 11  IPRI_bienes_consumo_no_duradero_2021                                                 615 non-null    float64
 12  año                                                                                  615 non-null    int32
 13  trimestre                                                                            615 non-null    int32
 14  periodo                                                                              615 non-null    object
dtypes: datetime64[ns](1), float64(11), int32(2), object(1)
memory usage: 67.4+ KB

### Eliminando la columna del indice de precios para suministro de agua, actividades de saneamiento, gestión de residuos y descontaminación,

Solo cuenta con datos a partir de 20073

In [55]:
df_75_26 = df_75_26.drop(columns= ['IPRI_suministro_agua_actividades_saneamiento_gestion_residuos_descontaminacion_2021'])

In [56]:
df_75_26.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 14 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   fecha                                                                615 non-null    datetime64[ns]
 1   IPRI_total_industria_2021                                            615 non-null    float64
 2   IPRI_industrias_extractivas_2021                                     615 non-null    float64
 3   IPRI_industria_manufacturera_2021                                    615 non-null    float64
 4   IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2021  615 non-null    float64
 5   IPRI_energia_2021                                                    615 non-null    float64
 6   IPRI_bienes_equipo_2021                                              615 non-null    float64
 7   IPRI_bienes_intermedios_2021                                         615 non-null    float64
 8   IPRI_bienes_consumo_2021                                             615 non-null    float64
 9   IPRI_bienes_consumo_duradero_2021                                    615 non-null    float64
 10  IPRI_bienes_consumo_no_duradero_2021                                 615 non-null    float64
 11  año                                                                  615 non-null    int32
 12  trimestre                                                            615 non-null    int32
 13  periodo                                                              615 non-null    object
dtypes: datetime64[ns](1), float64(10), int32(2), object(1)
memory usage: 62.6+ KB

### Cambio de base a 2025

In [57]:
fechas = [2025]
columnas_temporales = ['fecha', 'año', 'trimestre', 'periodo']

columnas_ipri = [col for col in df_75_26.columns if col not in columnas_temporales]

# Calcular medias y conversores para cada columna IPRI
for columna in columnas_ipri:
    for año in fechas:
        datos_año = df_75_26[df_75_26['año'] == año][columna]

        if len(datos_año) == 0:
            print(f'  ✗ {columna} | Año {año}: sin datos')
            continue

        media = datos_año.mean()
        n_meses = len(datos_año)
        completitud = 'año completo' if n_meses == 12 else f'{n_meses}/12 meses'

        # Conversor: para llevar valores nominales a precios del año base
        col_conv = columna.replace('_2021', f'_conversor_{año}')
        df_75_26[col_conv] = media / df_75_26[columna]

        # Índice rebasado: base año = 100
        col_rebased = columna.replace('_2021', f'_{año}')
        df_75_26[col_rebased] = (df_75_26[columna] / media) * 100

        print(f'  ✓ {columna} | {año}: media = {media:.4f} ({completitud})')

print()
print('Columnas nuevas:')
print([col for col in df_75_26.columns if col not in columnas_temporales + columnas_ipri])

  ✓ IPRI_total_industria_2021 | 2025: media = 125.4692 (año completo)
  ✓ IPRI_industrias_extractivas_2021 | 2025: media = 120.7542 (año completo)
  ✓ IPRI_industria_manufacturera_2021 | 2025: media = 118.8792 (año completo)
  ✓ IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2021 | 2025: media = 132.7042 (año completo)
  ✓ IPRI_energia_2021 | 2025: media = 133.0433 (año completo)
  ✓ IPRI_bienes_equipo_2021 | 2025: media = 113.0792 (año completo)
  ✓ IPRI_bienes_intermedios_2021 | 2025: media = 113.9783 (año completo)
  ✓ IPRI_bienes_consumo_2021 | 2025: media = 124.2750 (año completo)
  ✓ IPRI_bienes_consumo_duradero_2021 | 2025: media = 112.4633 (año completo)
  ✓ IPRI_bienes_consumo_no_duradero_2021 | 2025: media = 124.9225 (año completo)

Columnas nuevas:
['IPRI_total_industria_conversor_2025', 'IPRI_total_industria_2025', 'IPRI_industrias_extractivas_conversor_2025', 'IPRI_industrias_extractivas_2025', 'IPRI_industria_manufacturera_conversor_2025', 'IPRI_industria_manufacturera_2025', 'IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_conversor_2025', 'IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2025', 'IPRI_energia_conversor_2025', 'IPRI_energia_2025', 'IPRI_bienes_equipo_conversor_2025', 'IPRI_bienes_equipo_2025', 'IPRI_bienes_intermedios_conversor_2025', 'IPRI_bienes_intermedios_2025', 'IPRI_bienes_consumo_conversor_2025', 'IPRI_bienes_consumo_2025', 'IPRI_bienes_consumo_duradero_conversor_2025', 'IPRI_bienes_consumo_duradero_2025', 'IPRI_bienes_consumo_no_duradero_conversor_2025', 'IPRI_bienes_consumo_no_duradero_2025']

In [58]:
df_75_26 = df_75_26.filter(regex='^(?!.*conversor)')
orden = ['fecha', 'año', 'trimestre', 'periodo'] + [columna for columna in df_75_26.columns if columna.startswith('IPRI_')]
df_75_26 = df_75_26[orden]
df_75_26

,fecha,año,trimestre,periodo,IPRI_total_industria_2021,IPRI_industrias_extractivas_2021,IPRI_industria_manufacturera_2021,IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2021,IPRI_energia_2021,IPRI_bienes_equipo_2021,...,IPRI_total_industria_2025,IPRI_industrias_extractivas_2025,IPRI_industria_manufacturera_2025,IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2025,IPRI_energia_2025,IPRI_bienes_equipo_2025,IPRI_bienes_intermedios_2025,IPRI_bienes_consumo_2025,IPRI_bienes_consumo_duradero_2025,IPRI_bienes_consumo_no_duradero_2025
0,1975-01-01,1975,1,1975Q1,10.80,11.34,11.84,6.03,6.04,11.87,...,8.607692,9.390980,9.959693,4.543942,4.539874,10.497071,11.405677,9.688192,11.959453,9.413837
1,1975-02-01,1975,1,1975Q1,11.01,12.39,12.06,6.85,6.83,12.20,...,8.775064,10.260516,10.144755,5.161858,5.133666,10.788902,11.528507,9.752565,11.959453,9.541916
2,1975-03-01,1975,1,1975Q1,11.08,12.56,12.06,6.89,6.89,12.37,...,8.830855,10.401297,10.144755,5.192000,5.178764,10.939239,11.528507,9.816938,11.959453,9.541916
3,1975-04-01,1975,2,1975Q2,11.08,12.56,12.13,6.89,6.89,12.45,...,8.830855,10.401297,10.203638,5.192000,5.178764,11.009986,11.528507,9.881312,12.101722,9.661990
4,1975-05-01,1975,2,1975Q2,11.21,12.72,12.28,6.89,6.89,12.53,...,8.934466,10.533798,10.329817,5.192000,5.178764,11.080733,11.528507,10.010058,12.252882,9.790070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,2025-11-01,2025,4,2025Q4,124.77,121.48,119.27,127.26,130.27,113.70,...,99.442758,100.601083,100.328765,95.897516,97.915466,100.549025,99.334669,100.631664,100.326032,100.646401
611,2025-12-01,2025,4,2025Q4,125.23,121.32,118.42,133.30,131.75,113.85,...,99.809382,100.468583,99.613753,100.448994,99.027886,100.681676,99.545235,100.502917,100.459409,100.510316
612,2026-01-01,2026,1,2026Q1,125.89,123.08,118.97,134.24,132.40,114.56,...,100.335408,101.926090,100.076408,101.157336,99.516448,101.309555,100.440142,100.639710,101.810961,100.574356
613,2026-02-01,2026,1,2026Q1,122.13,124.44,119.81,113.53,119.26,114.73,...,97.338656,103.052345,100.783008,85.551195,89.639967,101.459892,101.001652,100.760410,101.882095,100.694431
614,2026-03-01,2026,1,2026Q1,130.04,124.61,126.27,126.60,143.91,114.83,...,103.642993,103.193127,106.217097,95.400170,108.167765,101.548325,102.001842,100.824784,102.219983,100.742460

In [59]:
df_75_26.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 24 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   fecha                                                                615 non-null    datetime64[ns]
 1   año                                                                  615 non-null    int32
 2   trimestre                                                            615 non-null    int32
 3   periodo                                                              615 non-null    object
 4   IPRI_total_industria_2021                                            615 non-null    float64
 5   IPRI_industrias_extractivas_2021                                     615 non-null    float64
 6   IPRI_industria_manufacturera_2021                                    615 non-null    float64
 7   IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2021  615 non-null    float64
 8   IPRI_energia_2021                                                    615 non-null    float64
 9   IPRI_bienes_equipo_2021                                              615 non-null    float64
 10  IPRI_bienes_intermedios_2021                                         615 non-null    float64
 11  IPRI_bienes_consumo_2021                                             615 non-null    float64
 12  IPRI_bienes_consumo_duradero_2021                                    615 non-null    float64
 13  IPRI_bienes_consumo_no_duradero_2021                                 615 non-null    float64
 14  IPRI_total_industria_2025                                            615 non-null    float64
 15  IPRI_industrias_extractivas_2025                                     615 non-null    float64
 16  IPRI_industria_manufacturera_2025                                    615 non-null    float64
 17  IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2025  615 non-null    float64
 18  IPRI_energia_2025                                                    615 non-null    float64
 19  IPRI_bienes_equipo_2025                                              615 non-null    float64
 20  IPRI_bienes_intermedios_2025                                         615 non-null    float64
 21  IPRI_bienes_consumo_2025                                             615 non-null    float64
 22  IPRI_bienes_consumo_duradero_2025                                    615 non-null    float64
 23  IPRI_bienes_consumo_no_duradero_2025                                 615 non-null    float64
dtypes: datetime64[ns](1), float64(20), int32(2), object(1)
memory usage: 110.6+ KB

# 4. Guardando el dataset final en un archivo

In [60]:
# ── Recortar al rango de tasa de paro y guardar en Datasets ────────────
from pathlib import Path
FECHA_INICIO = '1974-07-01'
FECHA_FIN    = '2025-10-01'
ruta_datasets = Path(r'C:\Users\marco\PycharmProjects\TFM_Marcos\Datasets')

df_final = df_75_26.copy()


df_75_26 = df_75_26[(df_75_26['fecha'] >= FECHA_INICIO) & (df_75_26['fecha'] <= FECHA_FIN)].copy()
df_75_26.to_csv(ruta_datasets / 'indice_precios_industriales_IPRI_bases_2021_2025.csv',
                index=False,
                encoding='utf-8-sig')

# 5. Información acerca del dataset final

In [61]:
df_final.attrs['nombre'] = 'df_final'
print('Información acerca del dataset final:')
print(f'{df_final.shape[0]} trimestres × {df_final.shape[1]} columnas | Rango: {df_final["fecha"].min().date()} → {df_final["fecha"].max().date()}')
columnas = df_final.columns.tolist()
print(f'  Columnas: {columnas}')
nulos = df_final.isna().sum()
nulos_col = nulos[nulos > 0]
if len(nulos_col) > 0:
    print(f'ALERTA  {df_final.attrs['nombre']}: nulos en {nulos_col.to_dict()}')
else:
    print(f'CORRECTO  {df_final.attrs['nombre']}: sin valores nulos')
print()

Información acerca del dataset final:
615 trimestres × 24 columnas | Rango: 1975-01-01 → 2026-03-01
  Columnas: ['fecha', 'año', 'trimestre', 'periodo', 'IPRI_total_industria_2021', 'IPRI_industrias_extractivas_2021', 'IPRI_industria_manufacturera_2021', 'IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2021', 'IPRI_energia_2021', 'IPRI_bienes_equipo_2021', 'IPRI_bienes_intermedios_2021', 'IPRI_bienes_consumo_2021', 'IPRI_bienes_consumo_duradero_2021', 'IPRI_bienes_consumo_no_duradero_2021', 'IPRI_total_industria_2025', 'IPRI_industrias_extractivas_2025', 'IPRI_industria_manufacturera_2025', 'IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2025', 'IPRI_energia_2025', 'IPRI_bienes_equipo_2025', 'IPRI_bienes_intermedios_2025', 'IPRI_bienes_consumo_2025', 'IPRI_bienes_consumo_duradero_2025', 'IPRI_bienes_consumo_no_duradero_2025']
CORRECTO  df_final: sin valores nulos

In [62]:
df_final.describe()

,fecha,año,trimestre,IPRI_total_industria_2021,IPRI_industrias_extractivas_2021,IPRI_industria_manufacturera_2021,IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2021,IPRI_energia_2021,IPRI_bienes_equipo_2021,IPRI_bienes_intermedios_2021,...,IPRI_total_industria_2025,IPRI_industrias_extractivas_2025,IPRI_industria_manufacturera_2025,IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2025,IPRI_energia_2025,IPRI_bienes_equipo_2025,IPRI_bienes_intermedios_2025,IPRI_bienes_consumo_2025,IPRI_bienes_consumo_duradero_2025,IPRI_bienes_consumo_no_duradero_2025
count,615,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000,...,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000
mean,2000-07-31 17:50:02.926829312,2000.126829,2.492683,63.902000,72.563236,66.962358,53.448878,54.797122,71.869854,65.176472,...,50.930441,60.091703,56.328085,40.276714,41.187424,63.557113,57.183212,55.219015,62.618132,54.598951
min,1975-01-01 00:00:00,1975.000000,1.000000,10.800000,11.340000,11.840000,6.030000,6.040000,11.870000,13.000000,...,8.607692,9.390980,9.959693,4.543942,4.539874,10.497071,11.405677,9.688192,11.959453,9.413837
25%,1987-10-16 12:00:00,1987.000000,1.000000,44.205000,58.930000,47.790000,33.140000,32.175000,55.480000,49.470000,...,35.231763,48.801629,40.200484,24.972841,24.183850,49.062972,43.402986,38.350433,48.060108,37.243091
50%,2000-08-01 00:00:00,2000.000000,2.000000,60.990000,70.710000,66.660000,43.360000,43.160000,76.940000,63.170000,...,48.609552,58.556986,56.073744,32.674181,32.440558,68.040827,55.422814,55.489841,64.918937,54.842002
75%,2013-05-16 12:00:00,2013.000000,3.000000,85.455000,96.475000,90.415000,71.170000,74.270000,93.110000,86.885000,...,68.108367,79.893723,76.056220,53.630569,55.823917,82.340543,76.229400,74.552404,81.986722,74.145971
max,2026-03-01 00:00:00,2026.000000,4.000000,143.470000,124.610000,126.270000,224.660000,210.360000,114.830000,123.740000,...,114.346818,103.193127,106.217097,169.293855,158.113898,101.548325,108.564493,101.412191,102.219983,101.574976
std,NaN,14.807016,1.121101,29.913927,27.432246,28.382932,36.608893,37.143635,26.941363,26.695838,...,23.841656,22.717432,23.875447,27.586845,27.918449,23.825223,23.421853,23.555782,23.322744,23.752407

In [63]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 24 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   fecha                                                                615 non-null    datetime64[ns]
 1   año                                                                  615 non-null    int32
 2   trimestre                                                            615 non-null    int32
 3   periodo                                                              615 non-null    object
 4   IPRI_total_industria_2021                                            615 non-null    float64
 5   IPRI_industrias_extractivas_2021                                     615 non-null    float64
 6   IPRI_industria_manufacturera_2021                                    615 non-null    float64
 7   IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2021  615 non-null    float64
 8   IPRI_energia_2021                                                    615 non-null    float64
 9   IPRI_bienes_equipo_2021                                              615 non-null    float64
 10  IPRI_bienes_intermedios_2021                                         615 non-null    float64
 11  IPRI_bienes_consumo_2021                                             615 non-null    float64
 12  IPRI_bienes_consumo_duradero_2021                                    615 non-null    float64
 13  IPRI_bienes_consumo_no_duradero_2021                                 615 non-null    float64
 14  IPRI_total_industria_2025                                            615 non-null    float64
 15  IPRI_industrias_extractivas_2025                                     615 non-null    float64
 16  IPRI_industria_manufacturera_2025                                    615 non-null    float64
 17  IPRI_suministro_energia_electrica_gas_vapor_aire_acondicionado_2025  615 non-null    float64
 18  IPRI_energia_2025                                                    615 non-null    float64
 19  IPRI_bienes_equipo_2025                                              615 non-null    float64
 20  IPRI_bienes_intermedios_2025                                         615 non-null    float64
 21  IPRI_bienes_consumo_2025                                             615 non-null    float64
 22  IPRI_bienes_consumo_duradero_2025                                    615 non-null    float64
 23  IPRI_bienes_consumo_no_duradero_2025                                 615 non-null    float64
dtypes: datetime64[ns](1), float64(20), int32(2), object(1)
memory usage: 110.6+ KB