# LIMPIEZA DE DATOS — TIPOS DE INTERÉS
### Interés legal del dinero e interés de demora tributario (be1901)
### Incluye:
- Importación de librerías
- Carga de datasets (formato Boletín Estadístico BdE)
- Conversión de tipos y limpieza
- Exportación de archivos finales

---
**Fuentes (Banco de España, Boletín Estadístico):**
- `tipos de interés. interés legal del dinero; interes de demora a efectos tributarios, BdE, be1901.csv`, *Tipos de interés: interés legal del dinero e interés de demora a efectos tributarios.* Anual.

# 0. Importación de "Librerías"

In [15]:
import pandas as pd
import plotly.express as px

# 1. Carga de datasets

In [16]:
ruta = '../Fuentes/BDE/TE_TIPOS/'

### Serie de 1973 a 2026

In [17]:
df_73_26 = pd.read_csv(ruta + 'tipos de interés. interés legal del dinero; interes de demora a efectos tributarios, BdE, be1901.csv', encoding= 'latin1', header=6)
df_73_26

         fecha  interes_legal  interes_demora_efectos_tributarios
0     1/1/1973           4.00                              4.0000
1     2/1/1973           4.00                              4.0000
2     3/1/1973           4.00                              4.0000
3     4/1/1973           4.00                              4.0000
4     5/1/1973           4.00                              4.0000
..         ...            ...                                 ...
635  12/1/2025           3.25                              4.0625
636   1/1/2026           3.25                              4.0625
637   2/1/2026           3.25                              4.0625
638   3/1/2026           3.25                              4.0625
639   4/1/2026           3.25                              4.0625

[640 rows x 3 columns]

In [18]:
df_73_26.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 3 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   fecha                               640 non-null    object
 1   interes_legal                       640 non-null    float64
 2   interes_demora_efectos_tributarios  640 non-null    float64
dtypes: float64(2), object(1)
memory usage: 15.1+ KB

### Chequeo en conjunto

In [19]:
dataframes = [df_73_26]

df_73_26.attrs['nombre'] = 'df_73_26'

In [20]:
# Valores únicos de cada dataset para ver las categorías
for df in dataframes:
    print(f'Valores únicos en {df.attrs['nombre']}')
    for columna in df:
        print(df[columna].unique())

Valores únicos en df_73_26
['1/1/1973' '2/1/1973' '3/1/1973' '4/1/1973' '5/1/1973' '6/1/1973'
 '7/1/1973' '8/1/1973' '9/1/1973' '10/1/1973' '11/1/1973' '12/1/1973'
 '1/1/1974' '2/1/1974' '3/1/1974' '4/1/1974' '5/1/1974' '6/1/1974'
 '7/1/1974' '8/1/1974' '9/1/1974' '10/1/1974' '11/1/1974' '12/1/1974'
 '1/1/1975' '2/1/1975' '3/1/1975' '4/1/1975' '5/1/1975' '6/1/1975'
 '7/1/1975' '8/1/1975' '9/1/1975' '10/1/1975' '11/1/1975' '12/1/1975'
 '1/1/1976' '2/1/1976' '3/1/1976' '4/1/1976' '5/1/1976' '6/1/1976'
 '7/1/1976' '8/1/1976' '9/1/1976' '10/1/1976' '11/1/1976' '12/1/1976'
 '1/1/1977' '2/1/1977' '3/1/1977' '4/1/1977' '5/1/1977' '6/1/1977'
 '7/1/1977' '8/1/1977' '9/1/1977' '10/1/1977' '11/1/1977' '12/1/1977'
 '1/1/1978' '2/1/1978' '3/1/1978' '4/1/1978' '5/1/1978' '6/1/1978'
 '7/1/1978' '8/1/1978' '9/1/1978' '10/1/1978' '11/1/1978' '12/1/1978'
 '1/1/1979' '2/1/1979' '3/1/1979' '4/1/1979' '5/1/1979' '6/1/1979'
 '7/1/1979' '8/1/1979' '9/1/1979' '10/1/1979' '11/1/1979' '12/1/1979'
 '1/1/1980' '2/1/1980' '3/1/1980' '4/1/1980' '5/1/1980' '6/1/1980'
 '7/1/1980' '8/1/1980' '9/1/1980' '10/1/1980' '11/1/1980' '12/1/1980'
 '1/1/1981' '2/1/1981' '3/1/1981' '4/1/1981' '5/1/1981' '6/1/1981'
 '7/1/1981' '8/1/1981' '9/1/1981' '10/1/1981' '11/1/1981' '12/1/1981'
 '1/1/1982' '2/1/1982' '3/1/1982' '4/1/1982' '5/1/1982' '6/1/1982'
 '7/1/1982' '8/1/1982' '9/1/1982' '10/1/1982' '11/1/1982' '12/1/1982'
 '1/1/1983' '2/1/1983' '3/1/1983' '4/1/1983' '5/1/1983' '6/1/1983'
 '7/1/1983' '8/1/1983' '9/1/1983' '10/1/1983' '11/1/1983' '12/1/1983'
 '1/1/1984' '2/1/1984' '3/1/1984' '4/1/1984' '5/1/1984' '6/1/1984'
 '7/1/1984' '8/1/1984' '9/1/1984' '10/1/1984' '11/1/1984' '12/1/1984'
 '1/1/1985' '2/1/1985' '3/1/1985' '4/1/1985' '5/1/1985' '6/1/1985'
 '7/1/1985' '8/1/1985' '9/1/1985' '10/1/1985' '11/1/1985' '12/1/1985'
 '1/1/1986' '2/1/1986' '3/1/1986' '4/1/1986' '5/1/1986' '6/1/1986'
 '7/1/1986' '8/1/1986' '9/1/1986' '10/1/1986' '11/1/1986' '12/1/1986'
 '1/1/1987' '2/1/1987' '3/1/1987' '4/1/1987' '5/1/1987' '6/1/1987'
 '7/1/1987' '8/1/1987' '9/1/1987' '10/1/1987' '11/1/1987' '12/1/1987'
 '1/1/1988' '2/1/1988' '3/1/1988' '4/1/1988' '5/1/1988' '6/1/1988'
 '7/1/1988' '8/1/1988' '9/1/1988' '10/1/1988' '11/1/1988' '12/1/1988'
 '1/1/1989' '2/1/1989' '3/1/1989' '4/1/1989' '5/1/1989' '6/1/1989'
 '7/1/1989' '8/1/1989' '9/1/1989' '10/1/1989' '11/1/1989' '12/1/1989'
 '1/1/1990' '2/1/1990' '3/1/1990' '4/1/1990' '5/1/1990' '6/1/1990'
 '7/1/1990' '8/1/1990' '9/1/1990' '10/1/1990' '11/1/1990' '12/1/1990'
 '1/1/1991' '2/1/1991' '3/1/1991' '4/1/1991' '5/1/1991' '6/1/1991'
 '7/1/1991' '8/1/1991' '9/1/1991' '10/1/1991' '11/1/1991' '12/1/1991'
 '1/1/1992' '2/1/1992' '3/1/1992' '4/1/1992' '5/1/1992' '6/1/1992'
 '7/1/1992' '8/1/1992' '9/1/1992' '10/1/1992' '11/1/1992' '12/1/1992'
 '1/1/1993' '2/1/1993' '3/1/1993' '4/1/1993' '5/1/1993' '6/1/1993'
 '7/1/1993' '8/1/1993' '9/1/1993' '10/1/1993' '11/1/1993' '12/1/1993'
 '1/1/1994' '2/1/1994' '3/1/1994' '4/1/1994' '5/1/1994' '6/1/1994'
 '7/1/1994' '8/1/1994' '9/1/1994' '10/1/1994' '11/1/1994' '12/1/1994'
 '1/1/1995' '2/1/1995' '3/1/1995' '4/1/1995' '5/1/1995' '6/1/1995'
 '7/1/1995' '8/1/1995' '9/1/1995' '10/1/1995' '11/1/1995' '12/1/1995'
 '1/1/1996' '2/1/1996' '3/1/1996' '4/1/1996' '5/1/1996' '6/1/1996'
 '7/1/1996' '8/1/1996' '9/1/1996' '10/1/1996' '11/1/1996' '12/1/1996'
 '1/1/1997' '2/1/1997' '3/1/1997' '4/1/1997' '5/1/1997' '6/1/1997'
 '7/1/1997' '8/1/1997' '9/1/1997' '10/1/1997' '11/1/1997' '12/1/1997'
 '1/1/1998' '2/1/1998' '3/1/1998' '4/1/1998' '5/1/1998' '6/1/1998'
 '7/1/1998' '8/1/1998' '9/1/1998' '10/1/1998' '11/1/1998' '12/1/1998'
 '1/1/1999' '2/1/1999' '3/1/1999' '4/1/1999' '5/1/1999' '6/1/1999'
 '7/1/1999' '8/1/1999' '9/1/1999' '10/1/1999' '11/1/1999' '12/1/1999'
 '1/1/2000' '2/1/2000' '3/1/2000' '4/1/2000' '5/1/2000' '6/1/2000'
 '7/1/2000' '8/1/2000' '9/1/2000' '10/1/2000' '11/1/2000' '12/1/2000'
 '1/1/2001' '2/1/2001' '3/1/2001' '4/1/2001' '5/1/2001' '6/1/2001'
 '7/1/2001' '8/1/2001' '9/1/2001' '10/1/2001' '11/1/2001' '12/1/2001'
 '1/1/2002' '2/1/2002' '3/1/2002' '4/1/2002' '5/1/2002' '6/1/2002'
 '7/1/2002' '8/1/2002' '9/1/2002' '10/1/2002' '11/1/2002' '12/1/2002'
 '1/1/2003' '2/1/2003' '3/1/2003' '4/1/2003' '5/1/2003' '6/1/2003'
 '7/1/2003' '8/1/2003' '9/1/2003' '10/1/2003' '11/1/2003' '12/1/2003'
 '1/1/2004' '2/1/2004' '3/1/2004' '4/1/2004' '5/1/2004' '6/1/2004'
 '7/1/2004' '8/1/2004' '9/1/2004' '10/1/2004' '11/1/2004' '12/1/2004'
 '1/1/2005' '2/1/2005' '3/1/2005' '4/1/2005' '5/1/2005' '6/1/2005'
 '7/1/2005' '8/1/2005' '9/1/2005' '10/1/2005' '11/1/2005' '12/1/2005'
 '1/1/2006' '2/1/2006' '3/1/2006' '4/1/2006' '5/1/2006' '6/1/2006'
 '7/1/2006' '8/1/2006' '9/1/2006' '10/1/2006' '11/1/2006' '12/1/2006'
 '1/1/2007' '2/1/2007' '3/1/2007' '4/1/2007' '5/1/2007' '6/1/2007'
 '7/1/2007' '8/1/2007' '9/1/2007' '10/1/2007' '11/1/2007' '12/1/2007'
 '1/1/2008' '2/1/2008' '3/1/2008' '4/1/2008' '5/1/2008' '6/1/2008'
 '7/1/2008' '8/1/2008' '9/1/2008' '10/1/2008' '11/1/2008' '12/1/2008'
 '1/1/2009' '2/1/2009' '3/1/2009' '4/1/2009' '5/1/2009' '6/1/2009'
 '7/1/2009' '8/1/2009' '9/1/2009' '10/1/2009' '11/1/2009' '12/1/2009'
 '1/1/2010' '2/1/2010' '3/1/2010' '4/1/2010' '5/1/2010' '6/1/2010'
 '7/1/2010' '8/1/2010' '9/1/2010' '10/1/2010' '11/1/2010' '12/1/2010'
 '1/1/2011' '2/1/2011' '3/1/2011' '4/1/2011' '5/1/2011' '6/1/2011'
 '7/1/2011' '8/1/2011' '9/1/2011' '10/1/2011' '11/1/2011' '12/1/2011'
 '1/1/2012' '2/1/2012' '3/1/2012' '4/1/2012' '5/1/2012' '6/1/2012'
 '7/1/2012' '8/1/2012' '9/1/2012' '10/1/2012' '11/1/2012' '12/1/2012'
 '1/1/2013' '2/1/2013' '3/1/2013' '4/1/2013' '5/1/2013' '6/1/2013'
 '7/1/2013' '8/1/2013' '9/1/2013' '10/1/2013' '11/1/2013' '12/1/2013'
 '1/1/2014' '2/1/2014' '3/1/2014' '4/1/2014' '5/1/2014' '6/1/2014'
 '7/1/2014' '8/1/2014' '9/1/2014' '10/1/2014' '11/1/2014' '12/1/2014'
 '1/1/2015' '2/1/2015' '3/1/2015' '4/1/2015' '5/1/2015' '6/1/2015'
 '7/1/2015' '8/1/2015' '9/1/2015' '10/1/2015' '11/1/2015' '12/1/2015'
 '1/1/2016' '2/1/2016' '3/1/2016' '4/1/2016' '5/1/2016' '6/1/2016'
 '7/1/2016' '8/1/2016' '9/1/2016' '10/1/2016' '11/1/2016' '12/1/2016'
 '1/1/2017' '2/1/2017' '3/1/2017' '4/1/2017' '5/1/2017' '6/1/2017'
 '7/1/2017' '8/1/2017' '9/1/2017' '10/1/2017' '11/1/2017' '12/1/2017'
 '1/1/2018' '2/1/2018' '3/1/2018' '4/1/2018' '5/1/2018' '6/1/2018'
 '7/1/2018' '8/1/2018' '9/1/2018' '10/1/2018' '11/1/2018' '12/1/2018'
 '1/1/2019' '2/1/2019' '3/1/2019' '4/1/2019' '5/1/2019' '6/1/2019'
 '7/1/2019' '8/1/2019' '9/1/2019' '10/1/2019' '11/1/2019' '12/1/2019'
 '1/1/2020' '2/1/2020' '3/1/2020' '4/1/2020' '5/1/2020' '6/1/2020'
 '7/1/2020' '8/1/2020' '9/1/2020' '10/1/2020' '11/1/2020' '12/1/2020'
 '1/1/2021' '2/1/2021' '3/1/2021' '4/1/2021' '5/1/2021' '6/1/2021'
 '7/1/2021' '8/1/2021' '9/1/2021' '10/1/2021' '11/1/2021' '12/1/2021'
 '1/1/2022' '2/1/2022' '3/1/2022' '4/1/2022' '5/1/2022' '6/1/2022'
 '7/1/2022' '8/1/2022' '9/1/2022' '10/1/2022' '11/1/2022' '12/1/2022'
 '1/1/2023' '2/1/2023' '3/1/2023' '4/1/2023' '5/1/2023' '6/1/2023'
 '7/1/2023' '8/1/2023' '9/1/2023' '10/1/2023' '11/1/2023' '12/1/2023'
 '1/1/2024' '2/1/2024' '3/1/2024' '4/1/2024' '5/1/2024' '6/1/2024'
 '7/1/2024' '8/1/2024' '9/1/2024' '10/1/2024' '11/1/2024' '12/1/2024'
 '1/1/2025' '2/1/2025' '3/1/2025' '4/1/2025' '5/1/2025' '6/1/2025'
 '7/1/2025' '8/1/2025' '9/1/2025' '10/1/2025' '11/1/2025' '12/1/2025'
 '1/1/2026' '2/1/2026' '3/1/2026' '4/1/2026']
[ 4.    8.   11.   10.5   9.5   9.   10.    7.5   5.5   4.25  3.75  5.
  3.5   3.    3.25]
[ 4.      7.      8.     11.     13.75   13.125  12.     11.5     9.5
  7.5     5.5     6.5     4.75    5.      6.25    4.375   3.75    4.0625]

In [21]:
# Información acerca del tipo de dato y valores nulos de las columnas de cada dataset
for df in dataframes:
    print(f'Información acerca de {df.attrs['nombre']}')
    print(df.info())

Información acerca de df_73_26
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 3 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   fecha                               640 non-null    object
 1   interes_legal                       640 non-null    float64
 2   interes_demora_efectos_tributarios  640 non-null    float64
dtypes: float64(2), object(1)
memory usage: 15.1+ KB
None

# 2. Limpieza

### Transformación de los datos de fecha

In [22]:
df_73_26['fecha'] = pd.to_datetime(df_73_26['fecha'])
df_73_26['año'] = df_73_26['fecha'].dt.year
df_73_26['trimestre'] = df_73_26['fecha'].dt.quarter
df_73_26['periodo'] = df_73_26['año'].astype(str) + 'Q' + df_73_26['trimestre'].astype(str)

df_73_26 = df_73_26.set_index('fecha').sort_index()
df_73_26 = df_73_26.reset_index()

print(f'Información acerca de {df_73_26.attrs['nombre']}')
print(df_73_26.info())

Información acerca de df_73_26
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 6 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   fecha                               640 non-null    datetime64[ns]
 1   interes_legal                       640 non-null    float64
 2   interes_demora_efectos_tributarios  640 non-null    float64
 3   año                                 640 non-null    int32
 4   trimestre                           640 non-null    int32
 5   periodo                             640 non-null    object
dtypes: datetime64[ns](1), float64(2), int32(2), object(1)
memory usage: 25.1+ KB
None

In [23]:
df_73_26.head()

,fecha,interes_legal,interes_demora_efectos_tributarios,año,trimestre,periodo
0,1973-01-01,4.0,4.0,1973,1,1973Q1
1,1973-02-01,4.0,4.0,1973,1,1973Q1
2,1973-03-01,4.0,4.0,1973,1,1973Q1
3,1973-04-01,4.0,4.0,1973,2,1973Q2
4,1973-05-01,4.0,4.0,1973,2,1973Q2

In [24]:
px.line(df_73_26, x='fecha', y=['interes_legal', 'interes_demora_efectos_tributarios'])

# 4. Guardando el dataset final en un archivo

In [25]:
# ── Recortar al rango de tasa de paro y guardar en Datasets ────────────
from pathlib import Path
FECHA_INICIO = '1974-07-01'
FECHA_FIN    = '2025-10-01'
ruta_datasets = Path(r'C:\Users\marco\PycharmProjects\TFM_Marcos\Datasets')

df_final = df_73_26.copy()


df_final = df_final[(df_final['fecha'] >= FECHA_INICIO) & (df_final['fecha'] <= FECHA_FIN)].copy()
df_final.to_csv(ruta_datasets / 'interes_legal_interes_demora_tributaria.csv',
                index=False,
                encoding='utf-8-sig')

# 5. Información acerca del dataset final

In [26]:
df_final.attrs['nombre'] = 'df_final'
print('Información acerca del dataset final:')
print(f'{df_final.shape[0]} trimestres × {df_final.shape[1]} columnas | Rango: {df_final["fecha"].min().date()} → {df_final["fecha"].max().date()}')
columnas = df_final.columns.tolist()
print(f'  Columnas: {columnas}')
nulos = df_final.isna().sum()
nulos_col = nulos[nulos > 0]
if len(nulos_col) > 0:
    print(f'ALERTA  {df_final.attrs['nombre']}: nulos en {nulos_col.to_dict()}')
else:
    print(f'CORRECTO  {df_final.attrs['nombre']}: sin valores nulos')
print()

Información acerca del dataset final:
616 trimestres × 6 columnas | Rango: 1974-07-01 → 2025-10-01
  Columnas: ['fecha', 'interes_legal', 'interes_demora_efectos_tributarios', 'año', 'trimestre', 'periodo']
CORRECTO  df_final: sin valores nulos

In [27]:
df_final.describe()

,fecha,interes_legal,interes_demora_efectos_tributarios,año,trimestre
count,616,616.000000,616.000000,616.000000,616.000000
mean,2000-02-15 07:59:13.246753280,5.365260,7.157265,1999.665584,2.504870
min,1974-07-01 00:00:00,3.000000,3.750000,1974.000000,1.000000
25%,1987-04-23 12:00:00,4.000000,5.000000,1987.000000,2.000000
50%,2000-02-15 12:00:00,4.000000,6.500000,2000.000000,3.000000
75%,2012-12-08 18:00:00,7.500000,9.500000,2012.250000,3.250000
max,2025-10-01 00:00:00,11.000000,13.750000,2025.000000,4.000000
std,NaN,2.529643,2.956826,14.834431,1.117478

In [28]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 616 entries, 18 to 633
Data columns (total 6 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   fecha                               616 non-null    datetime64[ns]
 1   interes_legal                       616 non-null    float64
 2   interes_demora_efectos_tributarios  616 non-null    float64
 3   año                                 616 non-null    int32
 4   trimestre                           616 non-null    int32
 5   periodo                             616 non-null    object
dtypes: datetime64[ns](1), float64(2), int32(2), object(1)
memory usage: 28.9+ KB